- gslib/commands/rb.py
See: https://codereview.appspot.com/187550043/
> Fixes incorrect rb command usage string

- gslib/__main__.py
- gslib/addlhelp/security.py
- gslib/boto_translation.py
- gslib/cloud_api.py
- gslib/cloud_api_delegator.py
- gslib/command.py
- gslib/command_runner.py
- gslib/gcs_json_api.py
- gslib/tests/test_trace.py
Used by Google Cloud Platform support to help troubleshoot customer issues.
> Add support for Google trace tokens

- gslib/commands/acl.py
recursive flag enables multithreading on bucket name as well
> clarifying the multithreading / sequential update

- gslib/commands/acl.py
same thing slightly different wording
> Updating wording according to suggestions by Mike

- gslib/commands/cp.py
- gslib/copy_helper.py
- gslib/tests/test_cp.py
Codereview Link: https://codereview.appspot.com/273010043/
Fixes #308
> Add -Z option to compress all files, regardless of extension

- gslib/commands/config.py
https://codereview.appspot.com/294720043/
> Disable all gsutil config flags except -a when running in the Cloud SDK.

- gslib/commands/rsync.py
- gslib/tests/test_rsync.py
The implementation is mostly copied from CpCommand.
> rsync: add support for canned ACLs

- gslib/__main__.py
OK, I squashed it and here is the change.
https://codereview.appspot.com/316490043/
> Add helpful error message when 'invalid_grant'. #423

- gslib/commands/config.py
- gslib/copy_helper.py
- gslib/tests/test_copy_helper_funcs.py
Related issue: https://codereview.appspot.com/335860043/
> Adds charset to Content-Type metadata field set through magic file detection

- gslib/commands/signurl.py
> Use HttpError.response instead of local response in signed url error message.

- gslib/addlhelp/command_opts.py
> rephrase -m is raising exception on error

- gslib/utils/posix_util.py
In certain scenarios, pwd.getpwuid() may be unable to find the user's
UID in the system user database, causing that method or any method that
uses it (e.g. getpass.getuser()) to raise a KeyError.
Also, we should be checking for `os.geteuid() == 0` to test if the user
is root on non-Windows systems.
> Fixes #575.

- gslib/addlhelp/crc32c.py
Fixes https://issuetracker.google.com/issues/110114343.
> Updates crcmod installation instructions.

- gslib/commands/rsync.py
- gslib/tests/test_rsync.py
> Add -u option to rsync, Skip files that are newer on the receiver.

- gslib/__main__.py
Fixes https://issuetracker.google.com/issues/80397917.
> Allows overriding Boto:ca_certificates_file via -o

- gslib/command.py
We use oauth2client, which has mechanisms in place to fall back to "pure
Python crypto" in the absence of pyOpenSSL -- additionally, this crypto lib is
only used for service account credential functionality. In those cases,
users would sometimes see the error:
AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
Random.atfork() should be called in both the parent and child process after
launching a new child process.
> Fixes #390.

- gslib/commands/du.py
- gslib/tests/test_du.py
> Fix du for 6-digit sizes (#613)

- gslib/boto_resumable_upload.py
- gslib/boto_translation.py
- gslib/commands/ls.py
- gslib/commands/signurl.py
- gslib/daisy_chain_wrapper.py
- gslib/gcs_json_api.py
- gslib/gcs_json_media.py
- gslib/tests/test_cp.py
- gslib/tests/test_du.py
- gslib/ui_controller.py
- test/gsutil_measure_imports.py
Let's try this again.... hopefully did it right this time!
> Select changes from 29e58c02

- gslib/tests/test_rsync.py
- gslib/tests/testcase/base.py
- gslib/tests/testcase/integration_testcase.py
- gslib/utils/text_util.py
This is a smaller one, but it's all I could get done before I catch my bus! More to follow tomorrow.
> Getting Py-Six-Current up to date - PR05

- gslib/commands/test.py
- gslib/utils/update_util.py
Found where the program prints out the failure message and returns a 1, even on passing tests.
> Fix failure flag

- .travis.yml
> Update TravisCI to use Xenial (Ubuntu 16.04)

- test/ci/kokoro/linux/continuous.sh
- test/ci/kokoro/linux/presubmit.sh
- test/ci/kokoro/linux/run_integ_tests.sh
- test/ci/kokoro/macos/continuous.sh
- test/ci/kokoro/macos/presubmit.sh
- test/ci/kokoro/macos/run_integ_tests.sh
This scripts have been moved into this repository for Kokoro
to run on its VMs each time a PR is submitted. These files were
moved into GitHub due to GCP VMs not having Piper access, per
b/123369015#comment13
> Added Kokoro integration test scripts.

- .gitmodules
- setup.py
Following the instructions from https://stackoverflow.com/questions/1260748/how-do-i-remove-a-submodule, because this was way harder than it should have been :upside_down_face: 
This is a follow-up to #645.
> Remove boto from git submodules.

- gslib/commands/rm.py
> Explicit wording in rm docs about deleting buckets

- gslib/commands/acl.py
- gslib/commands/bucketpolicyonly.py
- gslib/commands/mb.py
- gslib/commands/requesterpays.py
- gslib/commands/retention.py
- gslib/commands/versioning.py
These changes seem to make Sphinx happy, and I'm tired of dealing with
all the manual fixes to generated HTML docs.
> Fix docs formatting to convert to better HTML.

- gslib/utils/parallelism_framework_util.py
User reporting that this check crashes in FreeDesktop:
https://github.com/GoogleCloudPlatform/gsutil/issues/655
Cause: this check assumes that the first line is the correct line with
'NAME="<linux ver>"'. In most cases, this is correct, however this
assumption cannot be relied upon. Additional checks around the contents
of each line were added to look for 'NAME='.
Generic exception added to catch any other issues from this method in
the future (with exception information added to logging).
> Additional checks around ShouldProhibitMultiprocessing()

- gslib/commands/rsync.py
Fix two typos reported by users over in the c.g.c pages.
> Typo fixes

- gslib/commands/compose.py
Several of the limits around compose operations were lifted a few months ago.
> Update limits on compose operations

- test/ci/kokoro/windows/continuous.cfg
- test/ci/kokoro/windows/presubmit.cfg
- test/ci/kokoro/windows/py27_json.cfg
- test/ci/kokoro/windows/py27_xml.cfg
- test/ci/kokoro/windows/py35_json.cfg
- test/ci/kokoro/windows/py35_xml.cfg
- test/ci/kokoro/windows/py36_json.cfg
- test/ci/kokoro/windows/py36_xml.cfg
- test/ci/kokoro/windows/py37_json.cfg
- test/ci/kokoro/windows/py37_xml.cfg
- test/ci/kokoro/windows/run_integ_tests.bat
Kokoro looks specifically for a .bat script to run. I added this
.bat script to call our PowerShell script with appropriate params.
> [CI TESTING] Added .bat script for Windows tests

- setup.py
Updated submodule checkout as well as setup.py.
> Bump apitools to 0.5.27.

- test/ci/kokoro/windows/run_integ_tests.bat
Updated paths being passed to .ps1 script to specify full directory.
> Updated parameters passed to .ps1 script

- test/ci/kokoro/windows/run_integ_tests.ps1
This makes the script:
- Not print output of passing test groups (note that these are still
available in their corresponding log file though)
- Only print output for failing tests groups
- Print a final status (either FAILED or OK) at the end, along with
exiting with a non-zero exit code if it found that any tests failed
> Improve output of Windows integration test script

- test/ci/CI.md
Kokoro CI tests can be a little opaque, so I wrote some documentation around it.
> CI readme file

- gslib/utils/system_util.py
Tiny PR updating comment for changes in PR #755
> Updated version support comment

- gslib/utils/update_util.py
This fixes https://issuetracker.google.com/issues/135470907.
> Fix update command; allow detection of yapf files.

- gslib/commands/iam.py
Fixes https://issuetracker.google.com/issues/132280457.
> Fix unconverted markup to look better for web docs

- gslib/utils/boto_util.py
Fixes https://issuetracker.google.com/issues/135709541.
Python inconsistencies across versions == the worst.
> Sort the boto auth handlers in our patched method.

- gslib/tests/test_util.py
- gslib/utils/text_util.py
> Updated hex conversions

- gslib/commands/rsync.py
- gslib/tests/test_rsync.py
> Fix broken _UrlEncode(), improve docs, add tests.

- gslib/commands/hash.py
- gslib/commands/rsync.py
- gslib/commands/version.py
- gslib/gcs_json_api.py
- gslib/resumable_streaming_upload.py
- gslib/tests/test_cp.py
- gslib/tests/test_mv.py
- gslib/tests/test_rsync.py
- gslib/tests/test_ui.py
- gslib/tests/util.py
- gslib/utils/boto_util.py
- gslib/utils/copy_helper.py
- gslib/utils/hashing_helper.py
- gsutil.py
- setup.py
I rebased the changes from our py3-release-support branch back into master.   You've already reviewed all of these commits individually; this is just a PR for the overall merge.
> Merge py3 release support to master

- gslib/commands/iam.py
- gslib/gcs_json_api.py
- gslib/third_party/storage_apitools/storage_v1_client.py
- gslib/third_party/storage_apitools/storage_v1_messages.py
- gslib/utils/constants.py
b/135208774
go/iam-policy-version-integration
> Adding support for requestedPolicyVersion to storage.bucket.getIamPolicy

- gslib/daisy_chain_wrapper.py
- gslib/tests/test_cp.py
- gslib/tests/testcase/integration_testcase.py
https://issuetracker.google.com/issues/135959331
> Fixes bug where copying files > 100MiB from GCS to S3 hangs

- gslib/gcs_json_api.py
- gslib/third_party/storage_apitools/storage_v1_client.py
- gslib/third_party/storage_apitools/storage_v1_messages.py
> Changing requestedPolicyVersion to optionsRequestedPolicyVersion

- gslib/cloud_api.py
- gslib/cloud_api_delegator.py
- gslib/commands/config.py
- gslib/commands/hmac.py
- gslib/gcs_json_api.py
- gslib/tests/test_hmac.py
- gslib/third_party/storage_apitools/storage_v1_client.py
- gslib/third_party/storage_apitools/storage_v1_messages.py
Will be trying integration tests with pull with travis/kokoro
> Adding support for all service account hmac api commands

- gslib/commands/bucketpolicyonly.py
- gslib/commands/hmac.py
> Documentation updates for hmac, bucketpolicyonly, pre 4.41 doc release.

- gslib/__init__.py
- gslib/commands/iam.py
- gslib/utils/version_check.py
Will submit a follow-up PR soon with a pylintrc file and a script to run
it over all applicable files.
> Fix use-before-assignment pylint warnings.

- gslib/tests/testcase/unit_testcase.py
Fixes https://issuetracker.google.com/issues/129075385
> Fix occasional IOError in unittest tearDown in PY2

- .travis.yml
- gslib/boto_translation.py
- gslib/tests/test_cp.py
- gslib/tests/util.py
Fixes https://issuetracker.google.com/issues/138375199.
> Make TravisCI run pylint.

- gslib/tests/test_copy_helper_funcs.py
- gslib/tests/test_naming.py
- gslib/utils/copy_helper.py
Fixes https://issuetracker.google.com/issues/112817360 and #361
> Fix cp/mv; dest dir is a substring of another dir

- gslib/commands/config.py
- gslib/tests/test_util.py
- gslib/utils/boto_util.py
- Modified SetProxyInfo() to make it testable.
- Added test case(s) for SetProxyInfo()
- Added user friendly selections to proxy part of .boto file
> Added Test Case(s) for SetProxyInfo()

- gslib/tests/test_iam.py
- gslib/utils/iam_helper.py
Python 2 and 3 tests pass as per: https://g3doc.corp.google.com/cloud/storage/g3doc/internal/gsutil/gsutil-dev.md?cl=head#running-tests
(recreated now that confusion around desired behavior is resolved)
> add support for deleted members in the form deleted:...?uid=###

- gslib/utils/iam_helper.py
Otherwise we can't add domains.
> Add missing comma preventing changing domain permissions

- gslib/commands/du.py
This edit is in response to b/123531032
> State that `gsutil du` mimics `du -b` on Linux

- gslib/addlhelp/anon.py
--Consolidate Configuring/using credentials section
--Change point of view to second person
Associated bug: b/139329022
> Revise Accessing Public Data Without Credentials page

- gslib/tests/test_rsync.py
- gslib/utils/copy_helper.py
Fix for issue https://github.com/GoogleCloudPlatform/gsutil/issues/918
Rsync was throwing error when tried with a destination url which is a prefix of an existing object.
e.g if `gs://some_bucket/foobar` already exists, then doing the following would result in an error
```
gsutil rsync some_dir gs://some_bucket/foo
```
With this fix, the above command would be able to create a subdir `foo` and run rsync as if the directory `foo` exists.
Additional changes:
I noticed that for the test case `test_rsync_to_nonexistent_bucket`  https://github.com/GoogleCloudPlatform/gsutil/blob/0e0faf89474d591a4bd228775d4c9ac0f1ce5cbe/gslib/tests/test_rsync.py#L2564 the `_Check` function was not getting called. Added the call.
> Fix an issue with rsync throwing error when the destination url is a prefix of existing object.

- gslib/cloud_api_delegator.py
- gslib/wildcard_iterator.py
Updated rsa library to release-4.0. 
Dependent on https://github.com/gsutil-mirrors/rsa/pull/1
> Update rsa library to release-4.0

- gslib/commands/rewrite.py
> Note that rewrite -O option should be used for ubla buckets

- gslib/commands/rsync.py
> Improve rsync error text

- gslib/addlhelp/command_opts.py
- gslib/addlhelp/metadata.py
- gslib/commands/cp.py
- gslib/commands/notification.py
- gslib/commands/rsync.py
These changes backfill improvements made in cl/314212833, cl/314214939, cl/314216630, and cl/314217806.
> Make some more changes to the help files

- gslib/tests/test_Doption.py
- gslib/tests/test_user_agent_helper.py
- gslib/utils/user_agent_helper.py
Reverts GoogleCloudPlatform/gsutil#1017
Turning on new user agent fields.
> Revert "Turning off user agent changes temporarily"

- test/ci/kokoro/run_integ_tests.sh
> Set locale to utf8 for macos

- gslib/addlhelp/crc32c.py
- gslib/addlhelp/creds.py
- gslib/commands/rsync.py
Backfills identified while reviewing generated documentation output for the upcoming gsutil release.
> Backfill a few changes found in the cloud.google.com documentation

- gslib/commands/kms.py
- gslib/commands/rewrite.py
This addresses issue: https://issuetracker.google.com/issues/151814248
> Added options section to the Kms command

- gslib/commands/iam.py
- gslib/commands/rewrite.py
This addresses issue: https://issuetracker.google.com/issues/122078625
> Adding clarification regarding gsutil iam and it's -r option

- gslib/tests/test_cp.py
- gslib/tests/test_ls.py
Adds integration tests and update the boto submodule to include changes from boto [pr/12](https://github.com/gsutil-mirrors/boto/pull/12).
> Update boto submodule

- gslib/commands/du.py
- gslib/commands/kms.py
-- Backfill changes to kms.py originally made in cl/324688080.
-- Fix indenting for code example in du.py
> Small doc fixes

- gslib/boto_translation.py
- gslib/cloud_api.py
- gslib/cloud_api_delegator.py
- gslib/commands/signurl.py
- gslib/gcs_json_api.py
> Fix broken signurl error message.

- gslib/addlhelp/throttling.py
- gslib/commands/cp.py
- gslib/commands/mv.py
- gslib/commands/rewrite.py
- gslib/commands/rm.py
These changes have all recently been made to the cloud.google.com documentation and should be backfilled into the Github source files.
> Backfill several updates to reference docs

- gslib/commands/compose.py
- gslib/commands/cp.py
- gslib/commands/notification.py
Improvements and centralization of the discussion of parallel composite uploads.
> Backfill cl/335882034

- gslib/addlhelp/crc32c.py
Also remote a trailing whitespace and order imports.
> Correct a typo in documentation.

- gslib/commands/acl.py
This backfills changes made in CL 339944574.
> Update synopsis for acl.py

- gslib/tests/test_cp.py
- gslib/tests/test_encryption_helper.py
- gslib/utils/encryption_helper.py
- gslib/utils/hashing_helper.py
See https://github.com/GoogleCloudPlatform/gsutil/issues/1118.
> Fix base64.{encode/decode}string in python 3.9

- gslib/utils/copy_helper.py
Reverts GoogleCloudPlatform/gsutil#1077
> Revert "Prompt Daisy chain users to try STS"

- gslib/__main__.py
- gslib/context_config.py
- gslib/tests/test_mtls.py
- test/ci/kokoro/config_generator.sh
- test/ci/kokoro/linux/continuous.cfg
- test/ci/kokoro/linux/presubmit.cfg
- test/ci/kokoro/linux/py27_json.cfg
- test/ci/kokoro/linux/py35_json.cfg
- test/ci/kokoro/linux/py36_json.cfg
- test/ci/kokoro/linux/py37_json.cfg
- test/ci/kokoro/macos/continuous.cfg
- test/ci/kokoro/macos/presubmit.cfg
- test/ci/kokoro/macos/py27_json.cfg
- test/ci/kokoro/macos/py35_json.cfg
- test/ci/kokoro/macos/py36_json.cfg
- test/ci/kokoro/macos/py37_json.cfg
- test/ci/kokoro/run_integ_tests.sh
- test/ci/kokoro/windows/config_generator.ps1
- test/ci/kokoro/windows/continuous.cfg
- test/ci/kokoro/windows/presubmit.cfg
- test/ci/kokoro/windows/py27_json.cfg
- test/ci/kokoro/windows/py35_json.cfg
- test/ci/kokoro/windows/py36_json.cfg
- test/ci/kokoro/windows/py37_json.cfg
- test/ci/kokoro/windows/run_integ_tests.bat
E2E tests for new authentication method.
Based on: https://github.com/GoogleCloudPlatform/gsutil/pull/1122
> mTLS Part 3/3 E2E Tests

- gslib/gcs_json_api.py
- gslib/tests/test_cp.py
> Persist request reason header for resumable uploads and downloads.

- gslib/utils/update_util.py
Currently all auto-updates are broken due to this folder.
> Ignore the .github directory for updates

- gslib/boto_translation.py
- gslib/tests/test_encryption_helper.py
- gslib/utils/copy_helper.py
- gslib/utils/encryption_helper.py
- gslib/utils/hashing_helper.py
Looks like I missed a few in #1129. I confirmed that our tests pass with Python 3.9, so this should fix #1118.
> Fix more occurrences of encodestring/decodestring

- gslib/addlhelp/security.py
Avoid web doc generation removing our web docs note about the feature
> Add mTLS note to security docs

- gslib/commands/rsync.py
- gslib/tests/test_rsync.py
Added `--ignore-existing ` as in non-gsutil version of rsync.
Some times need rsync with GCS folder with many huge, immutable files. On first time dest don't have mtime and gsutil starting calculate checksum....
With  immutable files don't need check mtime and checksum.
Use case for this cassandra backups.
https://github.com/GoogleCloudPlatform/gsutil/issues/573
> rsync add ignore-existing option

- gslib/addlhelp/command_opts.py
- gslib/addlhelp/metadata.py
- gslib/commands/setmeta.py
These changes backfill edits made in CL 349374583 and CL 349633606.
> Update reference documentation related to metadata

- gslib/commands/ls.py
- gslib/commands/rsync.py
> Small doc edits to ls and rsync files

- gslib/addlhelp/versions.py
- gslib/addlhelp/wildcards.py
- gslib/commands/cp.py
- gslib/commands/rsync.py
This PR boils down the versioning and concurrency topic quite a bit and moves many of the finer details into online documentation.
> Backfill changes made in cl/360981741

- gslib/commands/kms.py
- gslib/commands/rm.py
Text clarification and link addition - these changes were made on cloud.google.com in cl/361923872 and cl/361923590.
> Backfill some small changes to gsutil reference docs

- gslib/addlhelp/retries.py
- gslib/tests/test_boto_util.py
- gslib/tests/test_cloud_api_delegator.py
- gslib/tests/test_command_runner.py
- gslib/tests/test_copy_helper_funcs.py
- gslib/tests/test_creds_config.py
- gslib/tests/test_gcs_json_api.py
- gslib/tests/test_gcs_json_media.py
- gslib/tests/test_ls.py
- gslib/tests/test_metrics.py
- gslib/tests/test_perfdiag.py
- gslib/tests/test_signurl.py
- gslib/tests/test_user_agent_helper.py
- gslib/tests/test_util.py
Recreated @karenarialin's PR b/c of unusual yapf error:
https://github.com/GoogleCloudPlatform/gsutil/pull/1213
Found that upgrading yapf, reformatting unrelated files, and
resubmitting worked.
> Retry strategy docs change w/ yapf upgrade

- gslib/addlhelp/wildcards.py
-- Combine notes in different parts of the page that convey the same information.
-- Remove future tense.
-- Replace some quotation marks with code blocks.
> Clean up the Wildcards help topic

- gslib/addlhelp/prod.py
- gslib/commands/cp.py
- gslib/commands/rsync.py
> Update links to retry documentation

- gslib/commands/mb.py
- gslib/commands/rb.py
- gslib/commands/rewrite.py
Addresses a few bugs we've received.
> Doc clarifications

- gslib/command.py
- gslib/tests/test_parallelism_framework.py
For transfers involving a large number of small files, the initial `-m` suggestion can scroll out of the screen really quickly, even with sequential execution. This PR makes it harder to miss by printing it every 1000 transfers or so.
This warning was also not covered by tests, so I added some.
> Improve parallelism suggestions

- gslib/boto_translation.py
Overwrite server-returned URL with custom endpoint for complex downloads (XML API).
gsutil doesn't have unit tests for the `boto_translation.py`, and it looks like we mostly rely on `cp` integration tests to cover `GetObjectMedia`.
I'm planning a design doc for E2E tests, so we should eventually get test coverage for all this code.
> XML API PSC Fix

- gslib/gcs_json_api.py
Builds on Apitools change:
https://github.com/google/apitools/commit/f11e0980af89428d3330bbe88702e011c505471c
> Enforce custom endpoints through multipart copies (JSON)

- gslib/addlhelp/wildcards.py
The current structure is somewhat redundant and confusing, plus it causes the c.g.c documentation to render incorrectly. This will address customer feedback received in b/186410170 (though it may or may not fix the rendering issue)
> Remove duplicate statement about wildcards

- gslib/gcs_json_media.py
- gslib/tests/test_gcs_json_media.py
> Ensure the correct content-length is provided for incomplete downloads.

- gslib/commands/web.py
Improvements and streamlining in the `gsutil web` documentation
> Backfill cl/373461623

- gslib/cloud_api_delegator.py
- gslib/tests/test_wildcard_iterator.py
- gslib/wildcard_iterator.py
Fixes https://github.com/GoogleCloudPlatform/gsutil/issues/1276 
See b/188835024 for more info.
> Make ** to represent zero or more folders for cloud urls

- gslib/commands/kms.py
See b/188929222 for background.
> Update warning text on KMS access denied

- gslib/tests/test_rewrite.py
Rewrite tests started failing because of a change in the way API no longer relies on KMS keys to trigger slow writes.
Check b/188451869
> Fix rewrite tests

- test/ci/kokoro/run_integ_tests.sh
See b/187701234#comment12 for context.
> Fix pyenv issue for macOS

- gslib/commands/cp.py
Backfills improvements made to cloud.google.com documentation.
> Small text tweak

- gslib/commands/notification.py
- gslib/commands/rsync.py
Backfills cl/381520147 and cl/381520313
> Backfill some small doc changes

- gslib/addlhelp/security.py
- gslib/commands/rewrite.py
Update files affected by the migration of the encryption keys page
> Backfill cl/381932961

- gslib/commands/notification.py
It looks like I garbled the sentence a bit in my previous edit
> Wording fix

- gslib/commands/test.py
- gslib/tests/test_context_config.py
- gslib/tests/testcase/base.py
Make NotParallelizable decorator work for classes and fix uncovered bugs.
> Make NotParallelizable decorator work for classes.

- gslib/utils/hashing_helper.py
> Change info log to debug log for hashing helper

- gslib/commands/logging.py
> Update intro for the gsutil logging command

- gslib/commands/ls.py
> Specify providers supported by gsutil ls

- gslib/commands/kms.py
> Improve and streamline `gsutil kms` reference doc

- setup.py
> Update mock library version

- gslib/commands/config.py
- gslib/commands/cp.py
- gslib/name_expansion.py
- gslib/tests/test_copy_helper_funcs.py
- gslib/tests/test_cp.py
- gslib/tests/test_stet_cp.py
- gslib/tests/test_stet_util.py
- gslib/utils/copy_helper.py
- gslib/utils/stet_util.py
Integration of STET binary with gsutil's cp command.
> STET flag and cp integration

- gslib/commands/config.py
- gslib/commands/cp.py
- gslib/tests/test_stet_cp.py
Reverts GoogleCloudPlatform/gsutil#1325
> Revert "Disable STET feature temporarily"

- gslib/addlhelp/command_opts.py
- gslib/commands/hmac.py
- gslib/commands/kms.py
- gslib/commands/mb.py
Clarify that project IDs or project numbers are accepted identifiers for a project
> Backfill cl/399213131

- gslib/addlhelp/crc32c.py
> Split crcmod instructions for Enterprise SUSE

- gslib/commands/rewrite.py
- gslib/commands/rm.py
> Improve `gsutil rm` and `gsutil rewrite` help pages.

- gslib/commands/iam.py
Doc changes described in https://critique-ng.corp.google.com/cl/402322145.
> Clarify usage of convenience values

- gslib/tests/test_perfdiag.py
Accommodate for certain Mac versions using IPv6 (`AF_INET6`) by default.
> Fix Mac Kokoro OSError.

- gslib/commands/cp.py
Outsource some of the conceptual details around resumable and streaming transfers
> Backfill cl/407385747

- gslib/commands/compose.py
Move detailed examples about the compose command into the linked concept doc.
> Backfill cl/409479748

- gslib/commands/du.py
Clarify versioning behavior in the du command
> Backfill cl/408715063

- gslib/commands/rsync.py
Doc improvements described in https://critique-ng.corp.google.com/cl/400760210.
> Docs improvements

- gslib/commands/notification.py
- gslib/tests/test_notification.py
> Fix splitting of -m flag

- gslib/command.py
- gslib/tests/test_command.py
- gslib/tests/test_shim_util.py
- gslib/utils/shim_util.py
Same as #1419
Revert of #1442
Just reverting the oauth2client changes that were accidentally added in #1419. Additonally addressing some review comments left on #1442
> Part 3 of shim for running gcloud storage: Translate top level flags and headers - Attempt 2

- gslib/commands/notification.py
- gslib/commands/pap.py
Backfill documentation changes that were revealed during the most recent generation of the c.g.c documentation
> Starsandskies backfills

- gslib/commands/cp.py
- gslib/commands/ls.py
- gslib/tests/test_cp.py
- gslib/tests/test_ls.py
- gslib/tests/test_shim_util.py
- gslib/tests/testcase/integration_testcase.py
- gslib/utils/shim_util.py
See b/206151616#comment2 for parity check results for ls
See b/206151615#comment2 for parity check results for cp
> Part 5 of shim for running gcloud storage: Test parity support

- gslib/addlhelp/wildcards.py
- gslib/commands/cp.py
Small clarifications to wildcard behavior in help documentation
> Backfill cl/425901984

- .gitmodules
- gslib/tests/test_util.py
- gsutil.py
Obviously wrong because there is no username before that password.
fixed by: https://github.com/httplib2/httplib2/pull/217
upstream issue: https://github.com/httplib2/httplib2/issues/218
> httplib2 was wrongly parsing `bar` in `bar@host` as password before v0.20.4

- gslib/commands/cp.py
- gslib/commands/mb.py
Backfill fixes noted in cl/433499889.
> Release fixes for help docs

- gslib/command.py
- gslib/commands/cp.py
- gslib/gcs_json_credentials.py
- gslib/utils/copy_helper.py
Adds some changes to assignment around `try-except` to  make Python 3.6 happy.
> Add cp -s flag to shim translation.

- gslib/commands/cp.py
- gslib/tests/test_cp.py
- gslib/utils/shim_util.py
Prep relevant tests for gcloud storage parity testing.
> Add cp -v and -n flags for shim translation.

- gslib/commands/cp.py
- gslib/commands/defstorageclass.py
- gslib/commands/ls.py
- gslib/commands/rm.py
- gslib/tests/test_defstorageclass.py
- gslib/tests/test_shim_util.py
- gslib/tests/testcase/integration_testcase.py
- gslib/utils/shim_util.py
See test parity results here: cl/440366504
> Add shim support for defstorageclass command

- gslib/commands/cp.py
- gslib/commands/rsync.py
- gslib/tests/test_posix_util.py
- gslib/tests/util.py
- gslib/utils/posix_util.py
Fetch umask once at the beginning of a copy rather than multiple times.
> Fetch umask once for preserve POSIX.

- gslib/commands/web.py
Also, shorten the command synopsis
> Backfill cl/444312484

- gslib/commands/cp.py
Test parity waiting for port of "acl" command.
Manually tested.
> Add shim support for cp ACL flags

- gslib/commands/notification.py
- gslib/tests/test_notification_pubsub.py
- gslib/tests/test_shim_util.py
- gslib/utils/shim_util.py
Adds a little infra for handling gsutil arguments that must be
compressed.
> Add shim support for notification commands.

- gslib/commands/kms.py
> Link to prereqs for using kms command

- gslib/commands/rb.py
- gslib/tests/test_cat.py
- gslib/tests/test_rb.py
Before, there was no translation mapping between gsutil and gcloud.
After, there is a translation mapping using the GcloudStorageMap class.
> Shim gsutil rb command.

- gslib/tests/test_ls.py
A few cases linger becuase of inability to test S3 and anonymous credentials.
> Complete more of ls test parity.

- gslib/commands/cp.py
Centralize the discussion of sliced object downloads in the webpage https://cloud.google.com/storage/docs/sliced-object-downloads
> Backfill cl/470082513

- gslib/commands/mb.py
- gslib/commands/pap.py
- gslib/tests/test_mb.py
- gslib/tests/test_shim_util.py
- gslib/utils/shim_util.py
Also fixes pap output issue and improves shim error message.
> Mb test parity minus retention.

- gslib/boto_translation.py
- gslib/cloud_api.py
- gslib/cloud_api_delegator.py
- gslib/command.py
- gslib/gcs_json_api.py
- gslib/tests/test_Doption.py
- gslib/tests/test_command.py
- gslib/tests/test_shim_util.py
- gslib/utils/translation_helper.py
Modify the gsutil-wide -h flag behavior to allow including arbitrary headers in http requests.
> Support arbitrary headers.

- gslib/addlhelp/shim.py
- gslib/commands/ls.py
Based on generation issues discovered in cl/476148114
> Small doc edits

- gslib/commands/bucketpolicyonly.py
- gslib/commands/ubla.py
Spoilers: The two commands are the same except for some changed display strings.
> Shim bucketpolicy only and ubla commands

- .github/workflows/ci.yml
- gslib/commands/rsync.py
- gslib/tests/test_rsync.py
- gslib/tests/test_wildcard_iterator.py
- gslib/tests/testcase/unit_testcase.py
- gslib/wildcard_iterator.py
> Fixes -x flag to address issue #1615

- gslib/commands/mv.py
https://github.com/GoogleCloudPlatform/gsutil/pull/1465 makes it possible to use wildcards in the source with directories (I believe, please correct me if I'm wrong).
> Remove restriction with using wildcards with directories

- gslib/addlhelp/crc32c.py
This error was noted in a piece of user feedback
> Fix capitalization for "Xcode"

- gslib/commands/mb.py
- gslib/commands/rpo.py
- gslib/tests/test_mb.py
- gslib/tests/test_rpo.py
- Add rpo flag shim translation for mb command
- Add unit test to test shim translation
- Add rpo get shim translation for rpo get command
- Fixed e2e tests
> Add shim translator for rpo flag in mb command

- gslib/commands/acl.py
- gslib/storage_url.py
- gslib/tests/test_acl.py
- gslib/tests/test_storage_url.py
Added shim tranlsator for GCS acl-file and test.
> ACL shim translator

- gslib/commands/acl.py
- gslib/commands/rpo.py
- gslib/tests/test_rpo.py
- Add unit test to test shim translation
- Fix incorrect test test_get_returns_default_for_dual_region_bucket
Depends on merging this [pr](https://github.com/GoogleCloudPlatform/gsutil/pull/1649) first
> Shim translator rpo set

- gslib/addlhelp/shim.py
- gslib/commands/autoclass.py
- gslib/commands/defacl.py
- gslib/commands/rsync.py
- gslib/tests/test_defacl.py
The formatter caught some issues in the `defacl.py` and `test_defacl.py` files. Documentation updates are in other files.
> Backfill documentation updates from release comments and fix formatting.

- gslib/command.py
- gslib/commands/config.py
- gslib/commands/cp.py
- gslib/commands/rsync.py
- gslib/tests/test_copy_helper_funcs.py
- gslib/tests/test_cp.py
- gslib/tests/test_rsync.py
- gslib/utils/copy_helper.py
Followup on #1655 to address #1663 and related issues.
> Make reauth check opt-in and silence non-auth-related exceptions.

- gslib/commands/rsync.py
> Update description of the `rsync -i` flag

- gslib/commands/hmac.py
- gslib/tests/test_hmac.py
> Add shim for hmac command

- gslib/commands/config.py
Response to late-breaking suggestions from @starsandskies. See #1682.
> Minor text changes to OAuth2 OOB changes

- gslib/commands/logging.py
Clean up the help documentation for `gsutil logging` a bit
> Backfill cl/526156014

- gslib/commands/du.py
- gslib/tests/test_du.py
All tests pass as they are with the current gcloud implementation.
> Du shim support and test parity.

- gslib/commands/cors.py
- gslib/commands/stat.py
Small format, tense, and terminology improvements to the stat and cors help pages
> Backfill cl/539110318

- gslib/commands/acl.py
Update acl.py to use snake case for "allUsers" and "allAuthenticatedUsers" (previously "AllUsers" and "AllAuthenticatedUsers").
> Update acl.py to use snake case "allUsers" and "allAuthenticatedUsers"

- gslib/commands/defstorageclass.py
- gslib/commands/notification.py
- gslib/commands/stat.py
- gslib/tests/test_acl.py
- gslib/tests/test_compose.py
- gslib/tests/test_cors.py
- gslib/tests/test_cp.py
- gslib/tests/test_iam.py
- gslib/tests/test_ls.py
- gslib/tests/test_stat.py
Fixes tests marked as passing that weren't actually passing.
> Parity fixes

- gslib/commands/acl.py
- gslib/commands/autoclass.py
- gslib/commands/compose.py
- gslib/commands/cors.py
- gslib/commands/defstorageclass.py
- gslib/commands/label.py
- gslib/commands/lifecycle.py
- gslib/commands/logging.py
- gslib/commands/web.py
- gslib/tests/test_acl.py
- gslib/tests/test_lifecycle.py
- gslib/tests/test_web.py
Also removing alpha from some commands that were missed in the previous pass.
> Using gsutil-like formatting for shimed cors,label,lifecycle,logging,web

- gslib/addlhelp/shim.py
Added some details related to authentication and credentials when the shim is in use.
> Add credentials information for shim

- gslib/gcs_json_api.py
- gslib/gcs_json_credentials.py
- gslib/tests/test_ls.py
- gslib/tests/util.py
- setup.py
1. Fixed a bug with downloading files from cloud with .p12 authentication.
2. Skip test which tests the caching behaviour of .p12 creds.
> Fixes the bug related to download, and upload files with .p12 authentication.

- CHANGES.md
Updated changes.md, and submodule gcs-oauth2-boto-plugin
> Updated changes.md, and submodule gcs-oauth2-boto-plugin

- gsutil.py
Modules Updated:
- chardet from 3.0.2 to 5.2.0
- charset_normalizer from 2.0.12 to 3.4.0
- requests from 2.27.1-10 to 2.32.3
- urllib3 from 1.26.9 to 2.2.2
- google-auth-library-python from 2.17.3 to 2.24.0
- boto from 2.49.0-98 to latest commit
> Update submodules for py3.12

- setup.py
Modules Updated:
- argcomplete from 1.9.4 to 3.5.1
- pyu2f from 0.1.3 to latest commit
- pyparsing from 2.4.7-2 to 3.1.4
- cachetools from 5.0.0 to 5.5.0
- certifi from 2023.07.22-9 to 2024.08.30
- idna from 3.3 to 3.10
- apitools from 0.5.32 to latest commit
- pyasn1 from 0.4.2 to 0.6.1
> Update submodules for py 3.12

- gslib/commands/mb.py
- gslib/tests/test_mb.py
> Add shim-translation for mb -s flag.

- gslib/commands/cp.py
- gslib/tests/test_cp.py
- gslib/tests/test_mv.py
Add shim translation for option -U in cp, and mv command
> Add shim translation for option -U in cp, and mv command
