GoogleCloudPlatform/gsutil

gslib/commands/signurl.py

The examples had the options after the first positional argument, which doesn't work with the command line parsing in gsutil.

Fixing signurl help synopsis and examples

---

gslib/commands/test.py
gslib/tests/testcase/integration_testcase.py

When ```gsutil test``` is executed as part of Cloud SDK installation, it gets the configured project ID as a ```-o GSUtil:default_project_id``` command line option.  It should pass the project ID down to the child test processes so that the child processes get this setting.
Tested as follows:
* Removed ```~/.boto``` file.  Modified my local Cloud SDK installation to make ```platform/gsutil``` point to the modified gsutil location.  Ran ```gcloud auth login``` and ```gcloud config set project <Project ID>``` in Cloud SDK environment with subsequent ```gsutil test -p16``` to test the wrapper flow.
* Ran ```./gsutil config``` to configure gsutil's credentials and project ID.  Ran ```./gsutil test -p16``` to verify that the tests still pass in this flow.

Propagate project ID configuration option to child test processes

---

gslib/commands/rsync.py

The docs said 
> matching any string ending in 'abc' would be specified using '.*abc'
but that will match "foo.abc.bar".

Fix rsync doc error about RE needed to match end of string

---

gslib/commands/help.py

Likewise, skip code to handle the PAGER environment variable that is unlikely to be set on Windows.

Avoid ANSI control codes in help on Windows

---

gslib/data/cacerts.txt

Removing the VeriSign Class 3 Public Primary Certification Authority
certificate since as of December 1, 2015, Symantec has decided that this
root will no longer comply with the CAB baseline requirements.
For more information, see:
https://googleonlinesecurity.blogspot.com/2015/12/proactive-measures-in-digital.html

Remove VeriSign Class 3 CA from trusted certs

---

gslib/commands/config.py

This mode generates a configuration file that doesn't have authentication configured. This mode is useful for users that need to manually configure authentication, or when running in a wrapped environment like the Cloud SDK.
https://codereview.appspot.com/283650043/

Add a new mode "-n" to gsutil config.

---

gslib/addlhelp/command_opts.py

Currently this text is somewhat malformed in the generated output at https://cloud.google.com/storage/docs/gsutil/addlhelp/TopLevelCommandLineOptions

Fix formatting of supported headers for gsutil -h flag

---

gslib/aclhelpers.py

Before this change:
```console
$ gsutil defacl ch -u foo@example.com:bar gs://example
CommandException: foo@example.com:bar is not a valid ACL change
Allowed permissions are READER, OWNER, OWNER, WRITER, OWNER, WRITER, READER
```
After this change:
```console
$ ./gsutil defacl ch -u foo@example.com:bar gs://example
CommandException: foo@example.com:bar is not a valid ACL change
Allowed permissions are OWNER, WRITER, READER
```

Reduce duplication in defacl ch error message

---

gslib/util.py

+ Recognize the "system" keyword in boto.cfg to support the use of the
system installed certs

- SSL certs

---

gslib/storage_url.py

This is consistent with other exception messages.
Because a dot is appended [when the exception is printed to the user](https://github.com/GoogleCloudPlatform/gsutil/blob/adf221296/gslib/__main__.py#L576), this prints two dots instead of one:
InvalidUrlError: . is an invalid root-level object name..
----
I’m submitting this PR directly because when I try to use Rietveld as [per your instructions](https://cloud.google.com/storage/docs/gsutil/addlhelp/ContributingCodetogsutil) it somehow doesn’t work:
```
$ ../rietveld/upload.py 
Upload server: codereview.appspot.com (change with -s/--server)
New issue subject: storage_url: Remove a trailing dot in an exception message
Email (login for uploading to codereview.appspot.com) [baptiste.fontaine@oscaro.com]: 
Password for …
```

storage_url: Remove a trailing dot in an exception message

---

gslib/boto_translation.py
gslib/cloud_api.py
gslib/cloud_api_delegator.py
gslib/command.py
gslib/commands/config.py
gslib/commands/cp.py
gslib/commands/perfdiag.py
gslib/commands/rsync.py
gslib/copy_helper.py
gslib/gcs_json_api.py
gslib/gcs_json_media.py
gslib/tests/test_copy_helper_funcs.py
gslib/tests/test_cp.py
gslib/tests/test_gcs_json_media.py
gslib/tests/test_perfdiag.py
gslib/tests/test_rsync.py
gslib/tests/test_util.py
gslib/tests/testcase/base.py
gslib/util.py

gsutil cp currently supports a combined gzip-compressed-and-stored encoding when uploading to Google Cloud Storage (GCS) via the -z/-Z arguments. This PR adds support for gzip-transport-compressed encoding when uploading to GCS.
Included:
- Integration with cp, rsync, and perfdiag commands.
- Resource limiting for parallel, transport compressed uploads.
Transport compressed uploads buffer data into memory to serve in a
chunked manor. For parallel uploads, many chunks may exist in memory
concurrently. To prevent excessive memory consumption, a lock is used
to restrict the number of transport compressed uploads that may be ran
in parallel.
- Dynamic progress printing for transport compressed uploads. To more
accurately represent the progress of a transport compressed upload, the
progress …

Add transport compression support.

---

.travis.yml
gslib/project_id.py
gslib/tests/testcase/unit_testcase.py

Making a pull request to ensure that unit tests still pass after the change to .travis.yml.

 Prevent unit tests from failing when no default project id is provided.

---

gslib/commands/rsync.py

When computing the MD5 or CRC32C of a file, we logger.info() to tell the user what's going on. The algorithm is mixed up on a couple of these messages, indicating MD5 when we're actually computing CRC32C, or vice versa.

Correct info log messages for computing checksums

---

gslib/addlhelp/crc32c.py
gslib/addlhelp/encoding.py
gslib/addlhelp/metadata.py
gslib/addlhelp/throttling.py
gslib/commands/config.py
gslib/commands/cp.py
gslib/tests/test_cp.py
gslib/utils/parallelism_framework_util.py

Apple rebranded Mac OS X as macOS. When referring to the operating system in general, we use macOS now.
https://developers.google.com/style/word-list#letter-M
This change is being made throughout our documents.

update references to Mac OS X

---

gslib/command.py

Tested locally:
```
$ ./gsutil -o GSUtil:x=y cp gs://pub/** /tmp/pub/
==> NOTE: You are performing a sequence of gsutil operations that may
run significantly faster if you instead use gsutil -m cp ... Please
see the -m section under "gsutil help options" for further information
about when gsutil -m can be advantageous.
```

Fix bug in gsutil -m note outputting first arg instead of command name.

---

gslib/commands/signurl.py

Former link:
https://cloud.google.com/storage/docs/bucket-locations
New link
https://cloud.google.com/storage/docs/locations

Fix link to storage 'locations' page

---

gslib/commands/mb.py

Former link:
https://cloud.google.com/storage/docs/bucket-locations
New link
https://cloud.google.com/storage/docs/locations

Fix link to storage 'locations' page (2)

---

setup.py

This is a follow-up to
https://github.com/GoogleCloudPlatform/gsutil/commit/19b55f9b7bb8c8daa1124ee17cb72a932475357e.

Bump apitools version to 0.5.25.

---

gslib/tests/test_cp.py
gslib/utils/copy_helper.py

As discussed in #591, `gsutil cp -n` will overwrite an existing local file if its size differs from the size of the source file.  This behavior is contrary to user expectations, POSIX convention, and the documentation.
Remove the special case for files with differing size, which was added in a768a58 to support resuming partial downloads.  This code has not been useful since 3e3d6dc, which started using temporary files (named with `_.gstmp`) for all downloads.
Fixes: #591
CC: @houglum
CC: @thobrla
Thanks for considering,
Kevin
P.S.:  To get any of the integration tests to run I had to apply boto/boto#3843.  I'm not sure why this apparently isn't affecting others.  Feel free to comment on that issue if you have any insights.

Fix #591: Don't clobber local files with differing size

---

setup.py

This allows us to pick up `ensure_text`, `ensure_binary`, etc. functions,
which will be helpful for the Python 2 -> "six" (2 and 3) migration
we're currently working on.
Bumped the version in setup.py and checked out the 1.12.0 tag from our
mirror, via `cd third_party/six; git fetch --tags origin; git checkout
1.12.0`.

Bump six version from 1.9.0 to 1.12.0.

---

gslib/commands/bucketpolicyonly.py

The old text was never changed after the command was revised to have two
subcommands. These changes make the explanations correct, as well as
isolating helptext between `get` and `set` so that `gsutil help
bucketpolicyonly get` and `gsutil help bucketpolicyonly set` will return
only the appropriate segments of the helptext.

Updates helptext for bucketpolicyonly command.

---

gslib/addlhelp/crc32c.py

CentOS 6 uses Python 2.6 by default (at least, it does on our GCE images).  This updates the instructions to show steps necessary to enable Python 2.7 for a session, as well as compiling/installing crcmod for Python 2.7.
This addresses https://issuetracker.google.com/issues/63114773

Update crcmod install instructions for CentOS 6

---

gslib/commands/bucketpolicyonly.py

Sending the extra bucket metadata causes more issues than it's worth and this is much closer to how versioning.py is implemented anyways.
Internal Issuetracker link: b/124315853

Update bucketpolicyonly set impl to not fetch bucket metadata before patching

---

gslib/commands/test.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/util.py

Commit cherry-picked: 779903967a1e2964a004665e4a3f7f285a62de25 by @walkerjoe 
The full python executable path was not propagating through to the test
processes and it was defaulting to Python2.7 even when the test was
started with python 3.x. Adding the path to the beginning of the cmd
sent to Popen forces the tests to use the correct python version.

Adding the python executable path

---

.gitignore
gslib/command_runner.py
gslib/commands/retention.py
gslib/commands/test.py
gslib/gcs_json_api.py
gslib/gcs_json_media.py
gslib/tests/test_cp.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/util.py
gslib/utils/retention_util.py

Cherry picked in 8 more commits, mostly small syntax changes. Most of the commits have a decent amount of context in their commit messages, but please feel free to ask for additional context. :smiley:
Changes include:
- Stubbed value for `encode_chunked` kwarg introduced in  3.6
- Added a (incomplete) skipped test printer for sequential tests
- Syntax fixes
- Encoding fixes
- String comparison method added for comparing possibly dissimilar types of strings (bytes vs unicode)
- `.gitignore` goodies

Python 3.x compat changes - encode_chunked stubbed, syntax fixes, encoding, and skipped test printing

---

gslib/commands/test.py
gslib/tests/test_cp.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/testcase/unit_testcase.py
gslib/utils/text_util.py

- 4faf087 Refactored; make get_random_ascii_chars method
> Made a new method get_random_ascii_chars as part of a small
> refactor. There was some minor redundant behavior. This method
> was made to follow DRY practices, and to increase readability.
- a194cc1 Unicode fix for Python 2
> One of the Unicode tests gets upset in Python 2.7 after recent
> commits. Explicitly specifying encoding makes it compatible
> across versions.
- 11e90c6 Unit test printer now safely concats strings
> Now using six.ensure_text to wrap test IDs before printing them
> in order to ensure compatibility between Python 2 and 3.
- 9921822 Refactored integ test for readability.
> While working with the integ test test_gzip_transport_encoded_upload_and_download
> I refactored it into several sub-methods, added …

Refactoring, encoding fixes, and concat fixes

---

test/RunParallelTestsOnWindows.ps1

See script details for why this is necessary.
This cuts runtime down from over an hour (running serially with
one process) to ~25 minutes.

Add ps1 script to run integ. tests in parallel

---

gslib/commands/perfdiag.py
gslib/utils/system_util.py

Perfdiag shouldn't run these commands on CI environments because we
probably (or at least, shouldn't) have permission to read/access
their compute resource metadata.
Also added a check for this to Kokoro - we're not using it yet, but this will
prevent the need for add'l changes once we get it working.

Don't run `gcloud compute` commands on CI envs.

---

.travis.yml

In anticipation of our upcoming Python 3.x support, this commit
adds support to have Travis run unit tests for versions of Python
greater than or equal to 3.5.
These versions are allowed to fail since we don't yet have full
support for Python 3.x. This file may be updated after we release
compatibility to the main branch.
`fail_fast` attribute was added so that Travis won't block PR
approval during allowed failures.

Updated Travis config to unit test Python >= 3.5, allowing errors from 3.x versions

---

gslib/utils/boto_util.py

Boto https connections weren't using SNI before. With the recent-ish
introduction of OpenSSL 1.1.1, we start to see SSL errors when making
requests to storage.googleapis.com (GCS's XML API) where the server
hostname was not specified. This pulls in
https://github.com/boto/boto/pull/3843 as a hotfix into gsutil, since
there isn't a released version of Boto where this PR is included yet,
and we'd like to have it sooner rather than later.

Fixes #606 - use SNI for boto cxns if possible

---

test/ci/kokoro/config_generator.sh

Added a shell script to be called by Kokoro when running
integration tests. It generates a config file allowing access
to the bigstore-gsutil-testing account.
Like the integ test shell scripts, this was pulled from Google3
due to GCP Kokoro VMs being unable to access Piper.

Added config generator for CI test scripts.

---

gslib/addlhelp/encoding.py
gslib/addlhelp/wildcards.py
gslib/commands/mb.py
gslib/commands/notification.py
gslib/commands/rsync.py

These fixes allow us to *correctly* generate web docs from the source
documentation.

Spacing fixes for docs, based on last release.

---

gslib/command.py

https://codereview.appspot.com/344170043/
Currently, when getting the default object ACL, the description only suggesting either the caller doesn't have OWNER permission or if the bucket has private ACL. 
This add information about Bucket Policy Only as one of the possible reason that default object ACL is empty.

Added details for Bucket Policy Only for defacl get.

---

test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/windows/presubmit.cfg

Before executing build scripts, Kokoro will now fetch keys from
keystore. Keys are stored in /src/keystore and should include a
key to access bigstore-gsutil-testing GCP account for access to
our testing infra, and a GitHub access key for Kokoro to monitor
and comment on our gsutil repository.
Docs: go/kokoro-keystore
ACLs: cl/236744745
Bug:  b/127358637

Kokoro builds now fetch keys from Keystore

---

test/ci/kokoro/windows/presubmit.cfg

Testing powershell script needs the Python path and gsutil directory
specified in its parameters. We're doing this in the build config
for Windows.
Build params kokoro doc: go/kokoro-build-params

Added param configs for Kokoro Windows jobs

---

test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/windows/presubmit.cfg

Build paths all have a typo, per b/127678469#comment7. This is
preventing Kokoro builds.

Updated Kokoro build script paths.

---

test/ci/kokoro/linux/continuous.cfg
test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/macos/continuous.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg

Added Kokoro CI build configs to trigger every time a push happens
on our repository. Although this will largely overlap with the
presubmit tests running on every PR, it may help us in the case of
code being pushed directly to the repo without a PR.

Added continuous build configs

---

test/ci/kokoro/linux/continuous.cfg
test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/macos/continuous.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg

In configs, fetching the GCP account key is mistakenly referencing
the keystore config name rather than the key name.
Our keystore keys can be found at go/gsutil-keystore-keyname

Updated keystore key name

---

gslib/third_party/storage_apitools/storage_v1_client.py
gslib/third_party/storage_apitools/storage_v1_messages.py

This change updates the JSON API client files in
gslib/third_party/storage_apitools to be consistent with the source
documents (via the JSON API discovery doc) and updates docstrings to
the new style that apitools generates (using raw strings), which makes
this change a bit noisy.
This commit also adds the "includeTrailingDelimiter" field to some
message types, but that is uninteresting because it's unused in the
code.

Update storage_v1_* apitools generated modules.

---

gslib/commands/version.py
gslib/utils/text_util.py

* Open file with utf-8 encoding when computing code checksum in commands/version.py.
* Try to write using default encoding in ttyprint, fallback to utf-8 if default is unsuccessful.
Both fixes are in response to errors found on Windows.

Encoding for win

---

test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

Added these configs so we can inject specific environment variables
into each child job, namely which Python version to use.
See: go/kokoro-env-vars
Note, these differ from the job configs in Google3 in two ways:
1. `find . -type f -name *.cfg -exec sed -i 's|https://INTERNAL_LINK.com|go/kokoro-env-vars|g' {} \;`
2. `find . -type f -name *.cfg -exec sed -i 's|allowed_env_vars|env_vars|g' {} \;`

Added configs for child jobs

---

gslib/commands/du.py
gslib/tests/testcase/integration_testcase.py

* Previous write to `sys.stdout.write` produced an error in windows, using ttyprint corrected the error.
* Previous method for gathering Pattern Exclusion only accepted UTF8, new method allows alternate encodings to be provided.
* Substituted map-lambda method and added try/except block for encoding

du windows fixes - text encoding

---

gslib/commands/du.py

Changes in response to Matt's comments
* Py2 has no `encoding` option in the `open` command. Added if/else case to handle both versions.
* `_GetPatternExclusion` was a copy-paste for the encode/decode logic and could have been revised and simplified in-line.
* `LOCAL_ENC` no longer needed (tested with mac/linux/win both py2 and 3 with no issues).

Du comment changes

---

gslib/utils/copy_helper.py

Windows with Python 3 adds a newline character at the end of a csv write
which can cause unexpected issues. Opening with newline specified as an
empty string can fix this issue.
REF: https://stackoverflow.com/questions/3191528/csv-in-python-adding-an-extra-carriage-return-on-windows

Newline added in Win/Py3 with CSV writer issue fixed.

---

test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

These were leftover when making the build configs based on the job
configs. It turns out that build configs don't have attributes for
type or group spec, only job configs.
Sponge log where we spotted this issue:
go/pr-remove-type-group-spec-sponge-log
Kokoro build proto:
go/kokoro-build

Removed `type` and `group_spec` from build configs

---

test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

Child build configs don't inherit from the build config defining
their job, so I'm manually prepending the needed fields.
Sponge logs: go/sponge-needs-build-file-prepend-pr
Sed command used to update these:
`find . -type f -name 'py*.cfg' -exec sed -i -e '1rcontinuous.cfg' -e
'1{h;d}' -e '2{x;G}'  {} \;`
This was tested on the `ci-testing` branch, yeilding output without
the previous error we were seeing.
I'll try to consolidate this pile of configs once things are running. :)

Prepended continuous config to child configs

---

test/ci/kokoro/linux/continuous.cfg
test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/continuous.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

After getting errors such as `AbortException: Build script does not exist: /tmp/workspace/workspace/cloud_storage_gsutil/linux/py27_json/src/github/test/ci/kokoro/linux/run_integ_tests.sh` in the Kokoro build logs, I updated the build script to use a relative path.
This was done with find / sed commands such as `find . -type f -name '*.cfg' -exec sed -i 's|test/ci/kokoro/linux/run_integ_tests.sh|./run_integ_tests.sh|g' {} \;`

Updating build script path to a relative path.

---

test/ci/kokoro/linux/continuous.cfg
test/ci/kokoro/linux/presubmit.cfg
test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/continuous.cfg
test/ci/kokoro/macos/presubmit.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

Kokoro evenually concatenates the relative path with the path its
tracking. Using the ./file notation, we started getting errors like:
`/tmp/workspace/workspace/cloud_storage_gsutil/linux/py27_json/src/github/./run_integ_tests.sh`
Removed instances of `./file` with just `file` using find -exec sed:
`find . -type f -name '*.cfg' -exec sed -i
's|\"./run_integ_tests|\"run_integ_tests|g' {} \;`

Relative path updated to not use ./

---

gslib/metrics.py
gslib/tests/testcase/integration_testcase.py

* Changes around submodule Popen to work with Windows / Py3
* Style Guide Indentation Change
* Standardize env_vars
* Add Raw String option
NOTE: All Metrics tests remain passing in macOS & Linux with the above changes

Metrics Test Fixes for Windows / py3

---

test/ci/kokoro/linux/py27_json.cfg
test/ci/kokoro/linux/py27_xml.cfg
test/ci/kokoro/linux/py35_json.cfg
test/ci/kokoro/linux/py35_xml.cfg
test/ci/kokoro/linux/py36_json.cfg
test/ci/kokoro/linux/py36_xml.cfg
test/ci/kokoro/linux/py37_json.cfg
test/ci/kokoro/linux/py37_xml.cfg
test/ci/kokoro/macos/py27_json.cfg
test/ci/kokoro/macos/py27_xml.cfg
test/ci/kokoro/macos/py35_json.cfg
test/ci/kokoro/macos/py35_xml.cfg
test/ci/kokoro/macos/py36_json.cfg
test/ci/kokoro/macos/py36_xml.cfg
test/ci/kokoro/macos/py37_json.cfg
test/ci/kokoro/macos/py37_xml.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

This commit comes in advance of some upcoming test script changes being run on the ci-testing branch.
.boto config files are now found in the path
/tmpfs/src/.boto_[json|xml]
These files were updated with find -exec sed:
`find . -type f -name '*.cfg' -exec sed -i
's|/src/config/.boto_json|/tmpfs/src/.boto_json|g' {} \;`
`find . -type f -name '*.cfg' -exec sed -i
's|/src/config/.boto_xml|/tmpfs/src/.boto_xml|g' {} \;`

Updated .boto config path in environment variables.

---

gslib/commands/rsync.py

In the event of a failure (e.g. due to encoding oddities), the only
thing you currently see is a one-line summary of the error. Seeing
exactly where the error came from would be more helpful for debugging.

Print trace in debug mode for rsync sync failures

---

gslib/commands/cp.py

The behavior has changed slightly over time, and the current documentation doesn't quite match the current behavior.

Fix description of the progress indicator bar

---

gslib/addlhelp/prod.py
gslib/addlhelp/versions.py
gslib/commands/acl.py
gslib/commands/cp.py
gslib/commands/stat.py
gslib/commands/versioning.py
gslib/commands/web.py

Fixes are based on open issues in the output documentation found on cloud.google.com.
Most edits are minor; the most significant change is to stat.py, which [I believe] contains outdated text about the consistency of bucket listing.

Bunch of small doc fixes.

---

gslib/utils/boto_util.py

Done via `cd gslib/vendored/boto; git pull`.  Commit hash is acd6a95.
Also remove some monkeypatches that we now have in our vendored
version of boto

Bump vendored boto lib to newest commit.

---

.travis.yml

py-six-current branch passes all unit tests in python 2 and 3 (hooray!)
so we should require python 3.x to pass all future tests.

Removed `allow_failures` for python 3 tests

---

test/ci/kokoro/linux/run_integ_tests.sh

We now export the BOTO_PATH environment variable
so gsutil will know what config to load. Doc:
https://cloud.google.com/storage/docs/boto-gsutil
A redundant call to `grep` was removed also, and a
call to `gsutil version -l` was added to more easily
see which config is being used at runtime.

Export BOTO_PATH environment variable

---

gslib/__main__.py
gslib/command_runner.py
gslib/commands/du.py
gslib/commands/hash.py
gslib/commands/help.py
gslib/commands/logging.py
gslib/commands/ls.py
gslib/commands/perfdiag.py
gslib/gcs_json_media.py
gslib/utils/cat_helper.py
gslib/utils/copy_helper.py
gslib/utils/ls_helper.py
gslib/utils/text_util.py

Note: haven't tested this refactor yet, putting this up for initial review, will work more on this after we have boto smoothed out.
Refactored ttyprint and ttywrite functions to be a little more
succinct and to utilize the available six.ensure_* functions.
Renamed ttyprint to print_to_fd and ttywrite to write_to_fd,
and updated references to tty*.

Refactored `ttyprint` and `ttywrite`

---

test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg
test/ci/kokoro/windows/run_integ_tests.bat

The config format we're using doesn't allow bash-style string
concatenation. As a result, we're instead building the path to
the Python executable on Windows using the PYMAJOR and PYMINOR
environment variables in the batch script calling our powershell
test runner.

Python exe path computed at runtime

---

gslib/commands/cp.py

These limits no longer apply in Cloud Storage.

Remove note about object composition limits.

---

test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

The BOTO_CONFIG environment variable is being calculated at
runtime in the run_integration_tests.bat file, so this environment
being set in the configs is not needed any longer.

Removed BOTO_CONFIG from Windows *.cfg

---

gslib/commands/iam.py

Fix indentation in `iam` command synopsis.

---

test/ci/kokoro/windows/config_generator.bat
test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg
test/ci/kokoro/windows/run_integ_tests.bat

Added a wrapper .bat script to call our powershell testing script.
Kokoro looks specifically for a .bat script to call. Additionally,
created a config generator for Windows and removed some environment
variables that are instead being calculated at runtime now.

Added Windows config generator, build wrapper

---

test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

Windows configs needed the full directory path *after* the local
T:\src\github but including the leading /src/ dir. After testing
on the ci-testing branches, Kokoro can find the build script with
this path.

[CI] Fixed path to Windows build file

---

gslib/commands/iam.py

This function was using itertools.izip which is only available on
Python 2.x. For compatibility, we're now using six.moves.zip.

Use compatibale six.moves.zip function

---

gslib/utils/text_util.py

For b/129794995 to fix failing `test_cp_resumable_upload_gzip_encoded_break`
get_random_ascii_characters actually needed to return a string
representation of a list of characters, rather than an actual
list of characters for our testing purposes. The logic has been
revised to represent this need, bearing closer to is original
authorship with some revisions for Python 3 compatibility.
For context, the original function in master branch looked like this:
```
random.seed(0)
contents = str([random.choice(string.ascii_letters)
for _ in xrange(self.halt_size)])
random.seed()  # Reset the seed for any other tests.
```
via https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/tests/test_cp.py#L1706

Revised get_random_ascii_characters function

---

gslib/__main__.py
gslib/tests/test_Doption.py
gslib/utils/system_util.py

Python 3 integration tests were looking for headers printed in
a slightly wrong order. Corrected the tests.
Bug: b/129722855
Test failure: Doption.TestDOption.test_minus_D_cat

Updated integ tests for Python 3

---

gslib/tests/testcase/base.py

Per b/129889537, Windows in Python 2.7 wouldn't correctly create
files with unicode characters. This is because the filename wasn't
being decoded before the temp file was being created. Added a
conditional decode to CreateTempFile in the base test case.

Decode filenames before creation

---

.travis.yml
gslib/boto_translation.py

Added `rewind=True` to `set_contents_from_file` args.

Fix perfdiag tests that were hitting eof and causing failures

---

gslib/tests/test_cp.py
gslib/tests/testcase/integration_testcase.py

The `RunGsUtil` method previously appended os.linesep to `stdin`s
that it encountered. This behavior doesn't reflect how Gsutil
actually operates and was removed.
This is a redo of PR #720 because new commits were merged to the head
of py-six-current and making a new PR is easier than doing a merge. :)
Bug: b/129889651

Remove newline concats to stdin

---

gslib/tests/test_Doption.py

Regex matching for test D option was broken in Python 2.x where
in some cases a string may be prepended by a u'' rather than the
expected b''.

Corrected regex matching in test output

---

gslib/utils/system_util.py

Some versions of python do not print values along with the keys
of headers returned. Original monkeypatch was only for 3.6.5, but
testing showed additional version of python also needed the fix.

Broaden `MonkeyPatchHttp()` for additional versions of Python3

---

gslib/tests/test_cp.py
gslib/utils/copy_helper.py

Previous logic was manually removing `b' '` from around strings that
weren't decoded. Refactored so that strings are decoded and don't need
to be stripped.
Bugs: b/130189680 , b/130189227

Refactored test_cp to decode strings

---

gslib/utils/text_util.py

While waiting for some tests to run, went ahead and replaced string literals `'utf-8'` in master branch with references to the constant `UTF8` from `gslib/utils/constants.py`.
These were found with `grep -Irn --exclude-dir third_party --exclude-dir vendored "'utf-8'" .` and replaced with `sed -i "s/'utf-8'/UTF8/g" ./utils/text_util.py`.

Replaced 'utf-8' literals with constant var

---

gslib/commands/config.py
gslib/gcs_json_api.py
gslib/tests/test_perfdiag.py
gslib/tests/testcase/integration_testcase.py

Add host header support for JSON, see issue: #727 
```
python gsutil.py -DD -o "Credentials:gs_json_host_header=www.googleapis.com" -o "Credentials:gs_json_host=restricted.googleapis.com" ls gs://
```

Add host header support for JSON

---

gslib/commands/rsync.py

For b/130244083
On the Py2/3 compat branch, rsync would crash when attempting to
recursively rsync a directory containing files with unicode in their
names. This was due to some temp file attributes not being properly
encoded.

Ensure unicode for rsync temp file attributes

---

README.md
gslib/addlhelp/dev.py
test/ci/CI.md

- Removed note from readme that we don't accept PRs
- Updated contributer guide to direct people to use PRs
- Added note about using `kokoro:run` tag to run CI on external contributions

Contribution doc updates

---

test/ci/kokoro/windows/continuous.cfg
test/ci/kokoro/windows/presubmit.cfg
test/ci/kokoro/windows/py27_json.cfg
test/ci/kokoro/windows/py27_xml.cfg
test/ci/kokoro/windows/py35_json.cfg
test/ci/kokoro/windows/py35_xml.cfg
test/ci/kokoro/windows/py36_json.cfg
test/ci/kokoro/windows/py36_xml.cfg
test/ci/kokoro/windows/py37_json.cfg
test/ci/kokoro/windows/py37_xml.cfg

Windows configs needed the full directory path *after* the local
T:\src\github but including the leading /src/ dir. After testing
on the ci-testing branches, Kokoro can find the build script with
this path.
This commit happened before, but I think I mowed it over in a
recent merge. Re-applying it to head with:
```
git checkout -b winbuild2 origin/master
git cherry-pick f30a5f0c4bbdad0692f07b4df553b165549a71c2 -X theirs
```

Fixed path to Windows build file (#710)

---

gslib/boto_resumable_upload.py
gslib/commands/ls.py
gslib/commands/perfdiag.py
gslib/commands/test.py
gslib/gcs_json_api.py
gslib/gcs_json_media.py
gslib/parallel_tracker_file.py
gslib/pubsub_api.py
gslib/resumable_streaming_upload.py
gslib/tests/test_acl.py
gslib/tests/test_bucketconfig.py
gslib/tests/test_cors.py
gslib/tests/test_cp.py
gslib/tests/test_du.py
gslib/tests/test_iam.py
gslib/tests/test_label.py
gslib/tests/test_naming.py
gslib/tests/test_requester_pays.py
gslib/tests/test_tracker_file.py
gslib/tests/test_ui.py
gslib/tests/test_update.py
gslib/tests/testcase/base.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/testcase/unit_testcase.py
gslib/tests/util.py
gslib/utils/boto_util.py
gslib/utils/constants.py
gslib/utils/hashing_helper.py

Replaced instances of `'utf-8'` string literals with calls to `constants.UTF8`. This is mainly to make code internally consistent.
Manually ran integ tests on Linux with Python 3.5 and 2.7 after the changes to make sure nothing broke. Will watch travis and kokoro results too.

Replaced 'utf-8' literals with constants.UTF8

---

test/ci/kokoro/windows/config_generator.ps1
test/ci/kokoro/windows/run_integ_tests.bat

For `b/130652316`
In Windows, specifying the notification URL seemed to be causing some 401 webhook errors, per the bug above. Removing the URL from the config seemed to make gsutil a little happier.
Additionally, added a line to the `run_integ_tests.bat` wrapper script to install `crcmod` before testing.
Sponge logs from test CI run: `go/gsutil-pr745-sponge`

[CI] Remove notification URL from config

---

gslib/tests/test_wildcard_iterator.py

For b/130652889
Sponge logs: go/gsutil-pr746-sponge
Wildcard iterator test was struggling with JSON objects on Kokoro's Windows. This looked like a thing we solved before, but may have gotten auto-merged badly at some point.

Ensure wildcard test objects are unicode

---

gslib/gcs_json_credentials.py

In Python 3.x, using gsutil with a keyfile in Windows environments causes an expected str() got bytes error. Using io.open() here helps alleviate this.
CI test logs to gsutil Windows runs, pointing to gcp/gsutil : ioopen branch, whose build script is modified to checkout gcs-oauth2 plugin on its own io.open branch: go/gsutil-ioopen-pr-logs
See also https://github.com/GoogleCloudPlatform/gcs-oauth2-boto-plugin/pull/44
For b/130652889

Use io.open for private keyfile

---

gslib/commands/cors.py

Users have been asking for more information on this page, so we can at least point them to the main GCS docs for additional material.

Link CORS command page to related GCS docs.

---

gslib/commands/config.py
gslib/utils/copy_helper.py

The current gzip compression level is 9, the python stdlib default, which is rather high. Reducing it to a more reasonable value - like 6, the default used by the gzip tool - improves compression speed substantially without losing much space.
In my use case, this improves gsutil end-to-end upload performance about one order of magnitude, though I suspect this will vary depending on compressibility of the files, which is why I'm not proposing changing the default.
With current defaults, uploading a 256MiB database file:
```
$ time ./gsutil cp -Z ~/Downloads/testfile-256Mi gs://jake-compressiontest
Copying file:///home/jake/Downloads/testfile-256Mi [Content-Type=application/octet-stream]...
Compressing file:///home/jake/Downloads/testfile-256Mi (to tmp)...
/ [1 files][ 28.1 MiB/ 28.1 MiB] …
```

Allow configuring compression level

---

gslib/utils/system_util.py

For b/131089489. HTTP headers print inconsistently between versions
of Python, which effects our test output when the -D flag is included.

Apply HTTP monkey patch to Python 3.7.0

---

MANIFEST.in
setup.py

End-users don't need stuff in the top-level test/ directory; likewise, the only
directory needed under gslib/vendored/boto/ is the boto/ directory.
Internal notes for Googlers: These changes were also included in our
tarball build script in changelist 244894227.

Fix setup.py to not package test and boto bloat.

---

gslib/commands/acl.py
gslib/commands/defacl.py

Make some minor fixes to the ACL command documentation:
* Fix ACL command synopsis - member flags are included redundantly, and two grants are missing the ":<perm>" portion.
* Fix branding - "Google Apps" should be "G Suite".
Synopsis.
* Link to documentation on available canned ACLs in both the `acl` command and `defacl` command options.

Acl doc updates

---

gslib/tests/test_cp.py
gslib/tests/test_rsync.py
gslib/tests/util.py

For b/131088388. When running cp, mv, or rsync with -P, sometimes
tests will fail due to how GID was computed. The expected GID was
taken from the current process's GID, while the file's actual GID may differ
if the /tmp dir is owned by a different group than the user's group who
launched the tests.
To rectify this, -P tests now compute expected GID by running stat
on the destination directory, and using its GID. The file being sent
to the cloud exists only in memory until it is downloaded.

Get GID for -P tests from dest dir

---

gslib/tests/test_ui.py

For b/131325628. We noticed in the CI pipeline on Windows that the test
test_ui_resumable_download_break_with_m_flag tended to flake fairly
frequently due to a race condition where the artifical download halt
signal was sent before the "0% Done" text was printed. Discussing with
Matt we agreed this assert didn't add very much value, and was fine to
simply remove.

Removed flaky assert

---

gslib/tests/test_ls.py

A blank ls command lists GS buckets, not S3 buckets. Fixes
https://issuetracker.google.com/issues/64948600.

Don't test blank ls command for S3 test mode.

---

gslib/tests/test_stat.py
gslib/tests/test_tabcomplete.py
gslib/tests/testcase/base.py
gslib/tests/testcase/integration_testcase.py
gslib/utils/text_util.py

For b/131254662.
Some tests that rely on tab-complete will fail when using the XML
API and when there are more than 1,000 buckets present. This is because
XML API does not accept prefixes for bucket names, it just returns a full list
off all buckets that gsutil filters to make tab complete work.
Since the list returned it alphabetized, as a workaround to the API limitation,
we append 'aaa-' to effected tabcomplete and wildcard tests to hoist their buckets
to the top of the list returned by the API.

XML >1k buckets test flake fix

---

gslib/tests/test_ui.py

Very similar to PR #764 , this removes an extra assert that tends to fail due to a race condition. Sometimes the artificial download halt will halt before the UI can produce the "0 / 1 files" string.

Fix flaky integ test on Windows

---

gslib/tests/test_rm.py

For b/131254662. When more than 1,000 buckets exist, the XML API returns
only the first 1,000. To workaround this, we prefix the bucket names
with 'aaa-' to help ensure these buckets will be in the first 1,000.

Fix rm wildcard bug with >1,000 buckets

---

gslib/commands/iam.py
gslib/utils/text_util.py

Reported in bug #770 , iam operations fail on buckets whose names don't
contain any letters. For example, bucket with a UID name that contains
only digits and dashes will throw an exception, since the iam command
will try to parse it as a binding rather than a URL.
See also b/132080434

Fix Iam Bucket URL Regex

---

gslib/tests/test_cp.py

For b/130055461. While doing Python 2/3 compat changes, we discovered
that the 'cp -L' flag had integration tests, but they failed to catch when headers
were wrapped in b' ' artifacts. This was because the asserts were only checking
a partial string slice. We fixed this by matching against the full source and dest.

Fixed integ test for 'cp -L' flag

---

gslib/commands/test.py

For b/132281242
Long running tests periodically print a "Still running" reminder. It
would be helpful to know how long they have been running for. This
commit adds the seconds elapsed since the process started to the
message.

Added time elapsed to 'Still running' messages.

---

gslib/commands/mv.py

While gsutil mimics a directory structure in some ways, it's more appropriate to think of it as common prefixes to object names.

Remove use of the term "subdirectories".

---

gslib/commands/kms.py

KMS keys should use specific locations (specifically, whatever location the data they apply to resides in), not the general "global" location.

Remove use of "global" in KMS key examples

---

gslib/commands/signurl.py

Fixes https://issuetracker.google.com/issues/133019153
Per the docs, the tilde character should not be percent-encoded:
When defining the path to the resource, you must percent encode the
following reserved characters: ?=!#$&'()*+,:;@[]."
https://cloud.google.com/storage/docs/access-control/signing-urls-manually
Note that Python 3's urllib quote method ignores the tilde, but Python
2's does not:
- Py2 docs: "Letters, digits, and the characters '_.-' are never quoted."
- Py3 docs: "Letters, digits, and the characters '_.-~' are never quoted."

Make signurl work with objects containing tildes.

---

gslib/commands/bucketpolicyonly.py
gslib/commands/cp.py
gslib/commands/notification.py

* Add the -j flag to the relevant example in `gsutil cp`.
* Clarify that `-m` is a top-level flag, not specific to `gsutil cp`.
* Offer links to additional conceptual information for the Bucket Policy Only and GCS-specific service account.
* These changes address the following user-reported issues: b/75005961, b/111501119, b/112908799, and b/131860498.

Small doc edits

---

gslib/gcs_json_credentials.py

When attempting to load a PKCS 12 key in Python 3, `io.open` would
throw an error since it tried to apply UTF-8 text encoding to the
key file, which was not a compatible text file.
Changes tested using .p12 key from our pre-release tests.

Improve logic for detecting PKCS 12 keys

---

gslib/commands/signurl.py
gslib/tests/test_update.py

The presence of many new scripts in the test directory upset and confused our pre-release tests. In this PR we're asking it not to look in this folder since it's all CI stuff that is tested separately anyways.
There was also a small bug with an earlier PR that introduced a regression for signing URLs in Python 2.x. Added a fix for this as well.

Remove test dir from test_update

---

gslib/__main__.py
gslib/tests/testcase/integration_testcase.py

We started running tabcomplete tests by specifying the interpreter used
to invoke gsutil; this ended up causing argcomplete to provide no
matches, as it was trying to find a Completer for something like "python
gsutil ls" (which didn't exist) rather than "gsutil ls" (which existed).
This is the 4th time I've had to do "clever" things to see what
argcomplete was printing out for me in order to debug test failures, so
I added in a boolean in the test code to toggle the add'l debug prints.

Add debugging mechanisms and fix tabcomplete tests.

---

gslib/tests/testcase/unit_testcase.py

On teardown when output is collected to be printed to stdout and stderr,
edge conditions can cause mixed bytes and unicode to be sent to the fd.
Adding several six.ensure_text calls to ensure all output is unicode
before attempting to write to FD.

Sanitize writes to FDs

---

gslib/tests/test_help.py

This will also be run against new commands added in the future, since
the list of commands is obtained by a call to `Command.__subclasses__()`.
Context: I found that the new hmac command failed when I tried to run
the help command against it.

Test `help` command for all commands.

---

gslib/tests/test_rsync.py
gslib/tests/test_update.py

For bugs:
https://github.com/GoogleCloudPlatform/gsutil/issues/807
b/135474885
Added a test case whith a file containing whitespace. A regression was
found that rsync tests didn't catch where split was called and
improperly parsed arguments when a file with whitespace was present.

Add file with whitespace in name to rsync tests

---

gslib/tests/testcase/unit_testcase.py
gslib/utils/text_util.py

For Python 2/3 compatibility, print_to_fd offers us more flexibility
when trying to write various string types to an arbitrary file
descriptor.
Also added get_utf8able_str function to try to ensure strings being
printed are in the right encoding, which cropped up a few times in
recent pre-release test runs where the deubg flag is included.

Replace sys.stderr.write with print_to_fd

---

gslib/tests/test_cp.py

Sometimes the resumable upload test would fail because it couldn't
artifically halt the test before finishing uploading the entire test
file. Made the test file much larger with more entropy to help avoid
this race condition.

Made resumable upload test use bigger file

---

gslib/tests/testcase/integration_testcase.py

Per b/29278122 and b/135780661, adding a timeout to Popen.communicate()
to prevent tests from hanging forever. TODO b/135936279, we should add
the timeout value to the .boto config file.
Note: The timeout keyword argument is only available in Python 3.

Add process timeout for tests

---

gslib/tests/test_cp.py
gslib/tests/test_iam.py
gslib/tests/test_rsync.py

Per b/135780661 and b/29278122, we sometimes see multiprocess testing on
nonexistent buckets hang. Timeouts have been added to the threads
running these tests, and now retry decorators are being added to the
tests themselves so they can attempt the test again after the previous
thread dies.

Added retry decorators to more tests

---

gslib/tests/test_tabcomplete.py
gslib/tests/testcase/base.py

Per PR 766's description, some XML tests fail when over 1000 buckets are
present. This is one of the tests that does this, and we hoist the
bucket name close to the top of the list py prefixing it with "aaa-".
Also fixed MakeTempName to always accommodate enough room for "aaa-".

Prefix invalid tabcomplete bucket name

---

gslib/tests/test_cors.py
gslib/tests/test_ls.py

In PR 826, I updated the temp bucket prefix logic to tuncate names a
little shorter to compensate for a specific test failure. This regressed
two other tests who had long statically defined names. These names were
shoretened to reflect the updated prefix logic.

Adjust wildcard bucket names

---

gslib/tests/test_cors.py
gslib/tests/test_cp.py
gslib/tests/test_iam.py
gslib/tests/test_rsync.py

This fixes an issue when running tests in Python 2.x. Also ran yapf on the test directory.

Move retry decorators into nested functions

---

gslib/commands/rsync.py
gslib/tests/test_rsync.py
gslib/tests/test_util.py
gslib/utils/text_util.py

Not sure why the hex stuff is showing up in the diff too; it's already in the GoogleCloudPlatform/py3-release-support branch.

Merge hex and url encoding changes

---

gslib/commands/rsync.py
gslib/tests/test_rsync.py

The tilde behavior was changed between 2 and 3; this also bit us in
another issue, see #783.

Make quote_plus behave the same on Python 2 and 3.

---

gslib/gcs_json_api.py
gslib/resumable_streaming_upload.py
gslib/tests/test_cp.py
gslib/tests/test_rsync.py
gslib/utils/copy_helper.py
gslib/utils/hashing_helper.py

This was causing a test to fail under Python 3. The underlying stream
was being treated as opened in text mode, rather than in binary mode,
because write_to_fd() could not determine its mode (and assumed text).
This caused sliced downloads to fail in
cp.TestCp.test_cp_resumable_download_gzip. Internal devs can see the
full failure stack trace and more details in this Issue Tracker issue:
https://issuetracker.google.com/issues/122963518#comment5

Add mode attribute to {up,down}load wrapper classes

---

MANIFEST.in
gslib/tests/test_update.py

This includes the update command (and its tests) and when building an
sdist release.  The MANIFEST.in changes were modeled after django's
MANIFEST.in file after reading a thread where they encountered this.
Fixes https://issuetracker.google.com/issues/136424742

Don't keep the pycache files when updating.

---

gslib/commands/notification.py

"projects.topics.publish" should be "pubsub.topics.publish"
See https://cloud.google.com/pubsub/docs/access-control#permissions for reference

Doc fix for notifications

---

gslib/__init__.py
gslib/tests/test_metrics.py
gslib/tests/util.py
gslib/utils/boto_util.py

Where appropriate, we now transform bytes from pkgutil.get_data into unicode
strings in Python 3 (this fixes issues where checksum and version strings
weren't the expected types - in the .par build, these were bytes (as the
documentation seems to indicate `get_data()` will return), but when run
locally under Python 3, they were unicode; these casts only happen when
the data should be converted to unicode and isn't already unicode).
Also, we now skip the metrics tests when running from a par file, since
the interpreter is nested within the archive (but it's needed to spawn
the metrics subprocess).

Fixes nits for .par bundles.

---

gslib/tests/test_copy_helper_funcs.py
gslib/utils/copy_helper.py

Fixes https://issuetracker.google.com/issues/136688879.
This was breaking internal builds where the subprocess that ran
`file` was returning a `bytes` instead of a `str` in stdout.
I was going to fix this in apitools:
https://github.com/google/apitools/pull/278
...but the call-site seems like a more appropriate place to do this.

Ensures we pass correct str type for content type.

---

gslib/commands/cp.py

Make it clearer that relevant examples pertain to uploading, which caused customer confusion in b/137530388.

Clarify what the initial `gsutil cp` examples do.

---

gslib/tests/testcase/integration_testcase.py

It does not exist on Windows, so the integration tests were failing.
Not sure why Kokoro was reporting successes; maybe it was only looking
up the status of the first tests to finish (which are usually the Linux
tests)?  Regardless, this fixes the issue of trying to call os.setsid on
Windows.

Only try calling os.setsid if that function exists

---

test/.pylintrc_limited
test/run_pylint.sh

Also adds a shell script that selects which files should be passed to
the linter.
Fixes https://issuetracker.google.com/issues/13656871.
TODOs:
- We still need to gradually go through the rest of the warnings that are
commented out and see which ones can safely be uncommented, which ones
are revealing actual issues, and which ones are just noise (and thus
should stay disabled) due to some of the odd imports and monkeypatching we do.
- We should also run this script as part of the TravisCI presubmits...
probably under both Python 2 and 3? I haven't tried running it under Py3
yet.
- All of the TODOs listed in the pylintrc file.

Add .pylintrc to check a subset of warnings.

---

gslib/commands/ls.py

If a `BucketListingRef`'s url string is already unicode, we shouldn't call
`decode()` on it. The `six.ensure_text()` call will only try to decode the
string-like object if it's a `bytes` type in Python 3, leaving it alone
if it's already `unicode`.
Should fix https://issuetracker.google.com/issues/138223113.

Prefer ensure_text() over explicit decode()

---

gslib/boto_translation.py
gslib/tests/testcase/integration_testcase.py

This was causing some perfdiag tests to fail, since we were trying to gzip encode a portion of the payload in an API request that didn't support it.

Make SkipForXML skip if running tests against S3.

---

gslib/addlhelp/metadata.py

-- Recommend "no-cache, max-age=0" instead of "private" for avoiding serving cached objects.
-- Add "private" and "public" to the Cache-Control parameters that the JSON API respects.
These changes address b/137487098 and b/137487793

Update documentation around Cache-Control

---

gslib/commands/acl.py
gslib/commands/bucketpolicyonly.py
gslib/commands/defacl.py
gslib/commands/hmac.py
gslib/commands/iam.py
gslib/commands/label.py

This fixes the formatting so that options tables are displayed correctly
(without leading and trailing rows) and indents commands so that they're
rendered as `<pre>` divs in the generated docs.

Update helptexts before release.

---

gslib/commands/config.py
gslib/utils/boto_util.py

The summary of changes made are listed below:
- Created a new Boto proxy variable proxy_type, where end users can specify one of (socks4, sock5 or http) proxy
- For backwards compatibility, proxy type configuration still defaults to http when proxy_type is not set.
- Created a new function SetProxyInfo() and moved proxy setting code from GetNewHttp(http_class=httplib2.Http, **kwargs) to the new function. Makes for a cleaner code.
- Third party library was throwing exceptions when rdns was enabled for socks proxy, so I limited rdns support to http/https proxies.
- For environment variables, only http/https is supported, pretty much did not to touch that part of the code.
- 
Fixes the following issue: gsutil socks proxy support needed #881

Support for socks proxy added

---

gslib/commands/ls.py
gslib/commands/mb.py

Standard is back in vogue. Meanwhile, Regional and Multi-Regional are not.

Update storage class names

---

gslib/commands/kms.py
gslib/tests/mock_cloud_api.py
gslib/tests/test_kms.py
gslib/tests/util.py

-w flag can be used for warning instead of erroring on updating key permissions failure

Add -w flag to kms encryption

---

gslib/commands/ubla.py
gslib/tests/test_ubla.py

Adds the ubla command to the gsutil api, currently this still sets the bucketPolicyOnly property on a bucket but as the two fields are interchangeable this is functionally equivalent. Once the api has been released allowing the use of uniform bucket-level access command a pull request will be made updating gsutil to use the new property.

Add the uniform bucket-level access command

---

gslib/utils/system_util.py

When trying a streaming upload through stdin, in a gsutil 4.43 installed through pypi in a python 3.7 environment, with the command
```
a_program | gsutil cp - gs://bucket/path
```
I'm getting the following error
```
...
File "/usr/local/lib/python3.7/site-packages/gslib/utils/hashing_helper.py", line 427, in read
data = self._orig_fp.read(size)
File "/usr/local/lib/python3.7/site-packages/gslib/resumable_streaming_upload.py", line 146, in read
data = b''.join(buffered_data)
TypeError: sequence item 0: expected a bytes-like object, str found
```
Trying to locate the cause of the error, I found that the stream is read through `sys.stdin.read()`, which in python 3 returns string objects instead of bytes. With this fix I no longer get an error and the upload finishes successfully.

Fix streaming upload in Python 3

---

gslib/tests/test_copy_helper_funcs.py
gslib/tests/test_naming.py
gslib/utils/copy_helper.py

The previously committed change caused a problem where running:
cp myFile gs://mybucket/nonExistentDir/
would create a file named "nonExistentDir" under "mybucket" instead of
creating "nonExistentDir/myFile".  Rather than try to special case this
I've just reverted part of the previous PR since expected behavior gets
gets ambiguous when providing multiple source files/directories.

Fix regression in cp caused by change #889.

---

gslib/tests/test_util.py
gslib/utils/boto_util.py

fixed default rdns behavior (as True) when http_proxy env variable is set, for backwards compatibility with 4.42 and below.
Fixes #913

fixed default rdns behavior (as True) when http_proxy env variable is set.

---

gslib/addlhelp/versions.py
gslib/commands/cp.py
gslib/commands/notification.py
gslib/commands/rewrite.py
gslib/commands/rsync.py

Instead of "archived" versions, refer to them as "noncurrent" versions. This will avoid terminology overload and matches equivalent changes being made to the documentation found in cloud.google.com/storage/docs
b/140083251 tracks the request to make this change.

Change object versioning terminology

---

gslib/commands/cp.py

Document that parallel composite uploads and bucket retention policies don't work well together. This edit backfills the changes made in cl/277526740.

Add warning to parallel uploads section

---

gslib/commands/bucketpolicyonly.py

--Change name from BPO to uniform bucket-level access
--Clarify that BPO is supported but UBLA is preferred
Parallel to changes made in cl/279111918

Clarify bucketpolicyonly name change to UBLA

---

gslib/commands/rsync.py

Removing the -d delete from the top section and moving it to it's own mirroring section.  The goal is to reduce confusion when people want to sync from source without deleting files and avoid accidental deletion. Internal CL approved: 284841364

Updating rsync to separate copy and mirror uses

---

gslib/commands/rsync.py

Example description for rsync -d is currently incorrect.
See cl/286629323

Swap source and destination in rsync description

---

gslib/addlhelp/encryption.py

Provide better linking to cloud.google.com concept pages. This edit mirrors changes made in cl/285488471

Update encryption key links

---

gslib/commands/cors.py

Mirrors changes to gsutil cors page made in cl/294304794.

Note that `storage.cloud.google.com` is incompatible with CORS

---

gslib/command_runner.py
gslib/commands/config.py
gslib/tests/test_cp.py
gslib/tests/test_metrics.py
gslib/tests/test_util.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/util.py
gslib/utils/copy_helper.py
gslib/wildcard_iterator.py

Previously keys were created in 'global', but global doesn't actually mean these keys can be used in any region. Switched the same default region for buckets.

KMS tests now create KMS keys in the same region as buckets

---

gslib/commands/iam.py

This addresses b/147214920, which noted the omission.

Add the -d flag to the options for `gsutil iam ch`

---

gslib/addlhelp/crc32c.py
gslib/addlhelp/encryption.py
gslib/commands/acl.py
gslib/commands/cat.py
gslib/commands/cp.py
gslib/commands/iam.py
gslib/commands/ls.py
gslib/commands/perfdiag.py
gslib/commands/rsync.py
gslib/commands/signurl.py
gslib/commands/stat.py
gslib/commands/update.py
gslib/commands/web.py

Additionally, place such callouts on their own lines in places where they're buried in a paragraph.
This formatting provides consistency in callouts and asides, and it should pave the way to addressing b/112876931.

All-caps note, caution, and warning callouts.

---

gslib/command_runner.py
gslib/commands/config.py
gslib/daisy_chain_wrapper.py
gslib/tests/test_cp.py
gslib/tests/test_metrics.py
gslib/tests/test_util.py
gslib/tests/util.py
gslib/utils/copy_helper.py
gslib/wildcard_iterator.py

Hi
I would like to contribute this patch to fix #935. 
This patch modified the initializer of `BufferWrapper` class in `gslib/daisy_chain_wrapper.py`, making it respect the wrapped class mode field or mode from input parameter. The input has a default value 'b' for mode.
With this change, the boto3 could correctly check buffer mode and do the things right under Python3 interpreter.
Please kindly review the patch.
Thanks

[Fix-Issue-935]: fix error while transferring binary from S3 with Python3

---

gslib/cloud_api.py
gslib/cloud_api_delegator.py
gslib/commands/signurl.py
gslib/gcs_json_api.py
gslib/iamcredentials_api.py
gslib/impersonation_credentials.py
gslib/tests/signurl_signatures.py
gslib/tests/test_signurl.py
gslib/tests/testcase/unit_testcase.py
gslib/utils/signurl_helper.py
gslib/utils/update_util.py

The `gsutil signurl` command uses the private key for a service account (the  '<key-file>' argument) to generate the cryptographic  signature for the generated URL. 
However, impersonated credential flow does not involve local credentials/certificates. The aim is to run `signurl` command without using a key-file. To support this,[ iamcredentials.signBlob()](https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob) can be used. This method Signs a blob using a service account's system-managed private key and does not require a key-file.
A flag `--use-service-account` or '-u' will be used to let gsutil know that the key file has not been provided. If a service account was impersonated, gsutil will use that account’s credentials to sign the url. If a …

Support service account impersonation for signurl in gsutil

---

.travis.yml
gslib/boto_translation.py
gslib/no_op_auth_plugin.py
gslib/tests/test_cp.py
gslib/tests/test_ls.py
gslib/tests/test_parallel_cp.py
gslib/tests/test_rm.py
gslib/tests/testcase/integration_testcase.py

Amazon S3 recommends using V4 signature for all the requests. The current implementation of our fork of [boto](https://github.com/gsutil-mirrors/boto) lib uses V2 signature by default for regions which support both V2 and V4 signature.
We have made changes to our boto fork to use V4 signature by default for all regions https://github.com/gsutil-mirrors/boto/pull/11
Using V4 signature makes some of the Integration tests in gsutil to break for S3, because boto lib does not play well with objects starting with slashes, among other things. Hence changes have been made in test cases to skip certain tests for S3 specifically.  The boto lib itself does not support objects starting with slashes, so it is safe to skip these tests for S3.

Use V4 signature as default for S3

---

gslib/tests/test_hash.py
gslib/tests/test_help.py
gslib/tests/test_kms.py
gslib/tests/test_naming.py
gslib/tests/test_parallel_cp.py
gslib/tests/testcase/unit_testcase.py

I changed the unit test base class to open stdout in `w+` mode instead of `wb+` mode. In doing so, we bring the fake stdout in line with that provided by `sys.stdout`, and cleans up our test cases since we don't need to explicitly convert all strings to bytes for comparison. 
This is compatible for both python 2 and 3 (note that the file descriptors have the same mode and system-dependent encoding)
```python
Python 2.7.17 (default, Dec 23 2019, 21:25:33)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.stdout
<open file '<stdout>', mode 'w' at 0x10e0511e0>
>>> open('/tmp/fakefile', 'w+')
<open file '/tmp/fakefile', mode 'w+' at 0x10e17b9c0>
```
```python
Python 3.7.7 …
```

Remove binary output assumption of stdout in tests

---

gslib/commands/kms.py
gslib/tests/test_kms.py

This addresses the ordering of the printed messages when the PatchBucket api call fails, since `text_util.print_to_fd` buffers in `stdout` until after the exception is raised to the user, which is printed to `stderr`.
This change depends on https://github.com/GoogleCloudPlatform/gsutil/pull/979

 Use print instead of text_util.print_to_fd in kms set encryption

---

gslib/commands/config.py
gslib/commands/cp.py
gslib/commands/rm.py

Typo fix, updated discussion of the -j and -z flags in "gsutil cp", and mention of the wildcard ** in "gsutil rm".
This PR backfills changes made in CL 306711352 and CL 305944510.

Small doc fixes

---

gslib/commands/bucketpolicyonly.py
gslib/commands/rsync.py

* Remove `` tags around "-d" in the section header of rsync: the tags were added to force the text to remain lowercase, but the docs generator still capitalizes it, so we'll rely on post processing to take care of this issue.
* Fix the URL tagging in ubla: the docs generator had trouble with the existing syntax. I think there needs to be a space after "command"

Small formatting fixes to the docs

---

test/ci/kokoro/run_integ_tests.sh

The kokoro build for MacOS was failing because of missing pyenv on the VMs.
Bug: b/154648156

Install pyenv if missing for kokoro

---

gslib/commands/signurl.py

The [signurl html documentation](https://cloud.google.com/storage/docs/gsutil/commands/signurl) is generated off of the help text present in the code. Recently the help text for updated directly. This fix brings the help text in sync with the html documentation.

Bring signurl help text in sync with html documentation

---

.gitmodules
gslib/__init__.py
gslib/cloud_api_delegator.py
gslib/tests/test_ls.py
gslib/wildcard_iterator.py
gsutil.py
setup.py

Fixes https://github.com/GoogleCloudPlatform/gsutil/issues/994
Depends on https://github.com/gsutil-mirrors/oauth2client/pull/1
Since https://github.com/googleapis/oauth2client is now archived and in read-only mode, we have decided to move the library code to the `gslib/vendored` section.

Fix oauth credfile permissions

---

gslib/gcs_json_api.py

When --use-service-account (-u) is used to sign URLs, allow debug
logging to record the Key ID used. This can then be looked up with
'gcloud iam service-accounts keys list' to find its expiration date.
b/154569245

Log GCS service-account key used to sign urls.

---

gslib/gcs_json_api.py

Moving the change made here https://github.com/GoogleCloudPlatform/gsutil/pull/1008 one level up. This way we are able to log the message for non-impersonated service account as well.

Log key id used for singurl in debug mode

---

gslib/commands/rsync.py

This fixes a bug with `rsync` where it was previously checking ACL's to determine whether a patch or rewrite should be applied. This didn't work at all in most cases and especially didn't work for UBLA buckets where object ACL's don't exist. Now we'll simply attempt a patch first before falling back to rewrites.

rsync now tries to patch before overwriting, rather than checking ACL

---

gslib/commands/signurl.py
gslib/tests/test_signurl.py

When -u flag is used, the SignBlob API is called, which guarantees the key's lifespan for up to 12 hours. This fix adds a restriction on the max duration allowed when the -u flag is used.
More info b/156160482

Signurl: Restrict duration to 12 hours when -u flag is used

---

gslib/addlhelp/apis.py
gslib/addlhelp/retries.py
gslib/commands/acl.py
gslib/commands/rsync.py

This backfills changes initially proposed in cl/310599519:
* Improved linking.
* Documenting HTTP 408 as retryable.
* Clarifying part of the `gsutil acl` synopsis.

Small doc edits.

---

gslib/commands/kms.py
gslib/commands/mb.py
gslib/commands/notification.py
gslib/commands/perfdiag.py

The PR fixes a few typos in command synopses as well as the formatting of a link in the `gsutil notification` file

Link and synopsis fixes in help text

---

gslib/__init__.py

[This line](https://github.com/GoogleCloudPlatform/gsutil/blob/4598a5cfb868201abc0de0226da96089adcbbd1a/gslib/third_party/storage_apitools/storage_v1_client.py#L38) makes `sphinx-build` break as `gslib.USER_AGENT` is created only when we run the gsutil command. 
This PR fixes that error by initializing `gslib.USER_AGENT` in `__init__.py`

Initialize user agent to fix a web doc generation error

---

gslib/commands/iam.py

We don't print the usage synopsis when the user incorrectly enters `gsutil iam` arguments.
http://b/150976767

Add usage synopsis to iam

---

setup.py

RSA dropped support for python 2 (see the Major changes in 4.1 section [here](https://pypi.org/project/rsa/4.1.1/)), and the latest version of the library includes type annotations that cause travis to fail ([log](https://travisci.org/github/GoogleCloudPlatform/gsutil/jobs/697669414#L431)). To ensure python 2 compatibility we need to use a previous version of rsa. 
It would be cleanest to do this in the dependency that requires rsa: `gcs-oauth2-boto-plugin`, but as it will take some time to upload that to pypi I am including a quick fix here, to be removed when gcs-oauth2-boto-plugin is updated.

Cap rsa version at 4.0

---

gslib/commands/stat.py

https://issuetracker.google.com/issues/158692016
Fixes a problem where the `stat` command did not add a new line after certain errors were logged, e.g.:
```
prompt $ gsutil stat s3://asdf/test3.txt
You aren't authorized to read s3://asdf/test3.txt - skippingNo URLs matched: s3://asdf/test3.txtprompt $
```
After this change the same command outputs the following:
```
prompt $ gsutil stat s3://asdf/test3.txt
You aren't authorized to read s3://asdf/test3.txt - skipping
No URLs matched: s3://asdf/test3.txt
prompt $
```

Add new line after stat error output

---

gslib/commands/rm.py
gslib/exception.py
gslib/tests/test_naming.py
gslib/tests/test_rm.py

Make error message more clear for case where user tries to copy, and source files do not exist.
http://b/150820007

Better error message for cp with empty source directory

---

gslib/addlhelp/encoding.py

native2ascii docs change.

---

gslib/commands/rsync.py
gslib/sig_handling.py

https://issuetracker.google.com/issues/148845060
`gsutil rsync -d src dest` currently raises an `OSError` if it is retried after being interrupted. This is because if there's a file `name.txt` in `src` not present in `dest`, `rsync` makes a call to copy, which generates a `name.txt_.gstmp` file in `dest` that is used to hold data during a transfer. the `_.gstmp` file is renamed `name.txt` after the transfer is completed, but if the transfer is interrupted the file is never renamed. 
When `gsutil rsync -d src dest` is retried after being interrupted, it first builds a diff between the two directories, scheduling `name.txt_.gstmp` for deletion. The problem arises when the copy occurs before the remove operation, since copy will delete the `name.txt_.gstmp,` causing the rsync remove step to …

Fix OSError on interrupted rsync -d

---

gslib/addlhelp/metadata.py
gslib/commands/config.py
gslib/commands/mb.py

This change backfills CL 315936810, which moves information about the configuration file into a dedicated page at https://cloud.google.com/storage/docs/boto-gsutil

Update help text about the boto configuration file

---

gslib/commands/cp.py
gslib/utils/copy_helper.py

See title. Basically if you invoke `gsutil cp` from 2 different processes to copy files into the same non-existent destination directory, there's a potential race condition in creating the destination directory(s). This is the thread-safe directory creation method thats compatible with python 2.7.

Fix multithread race condition for cp/mv command when multiple operations are attempting to create the same directory

---

gslib/commands/setmeta.py
gslib/third_party/storage_apitools/storage_v1_messages.py
gslib/utils/ls_helper.py
gslib/utils/translation_helper.py

b/158838040
Integrates new metadata field with `setmeta` and `ls` commands.
```
$ gsutil setmeta -h custom-time:2045-10-02T10:00:00-05:00 gs://mybucket/hi.txt
Setting metadata on gs://mybucket/hi.txt...
/ [1 objects]                                                                   
Operation completed over 1 objects.
$ gsutil ls -L gs://mybucket/hi.txt
gs://mybucket/hi.txt:
Creation time:          Fri, 12 Jun 2020 21:22:19 GMT
Update time:            Mon, 22 Jun 2020 17:54:29 GMT
Storage class:          NEARLINE
Content-Language:       en
Content-Length:         0
Content-Type:           text/plain
Custom-Time:            2045-10-02 15:00:00+00:00
....
```

Add support for custom-time metadata

---

.travis.yml
gslib/commands/hash.py

The stdout and stderr ordering gets messed up in Python3 as shown below. b/147895168. This happens because for python3, the [print_to_fd](https://github.com/GoogleCloudPlatform/gsutil/blob/05b4c88e53e21d9b919111500594d4547f48f44f/gslib/commands/hash.py#L226) function writes to stdout.buffer instead of stdout directly which causes content from `sys.stderr` to show before `sys.stdout`
Before:
```
$ python2 ./gsutil hash ~/temp/junk/chair.png
Hashes [base64] for /usr/local/google/home/dpednekar/temp/junk/chair.png:
Hash (crc32c):          Yd1Nag==
Hash (md5):             z2yKupEgoWkutTtcBMgpoQ==
Operation completed over 1 objects/3.3 KiB.
$ python3 ./gsutil hash ~/temp/junk/chair.png
/ [1 files][  3.3 KiB/  3.3 KiB]
Operation completed over 1 objects/3.3 KiB.
Hashes [base64] for …
```

Fix stdout ordering issue in hash command

---

gslib/tests/testcase/integration_testcase.py

Boto falls back on other credentials files or environment variables when fields aren't present in a Boto config file.
For those with AWS CLI installed, this meant an `~/.aws/credentials` file was giving Boto credentials even when we tried to anonymize a test client.
Documentation:
http://boto.cloudhackers.com/en/latest/boto_config_tut.html

Fix tests using wrong AWS credentials.

---

gslib/tests/test_user_agent_helper.py

I cases where tests are run via a version of Gsutil invoked via CloudSDK, the user agent will have a CloudSDK suffix appended, which will interfere with a `$` in regex comparisons of the resulting user agent string. I've now mocked out the CloudSDK detection completely in cases where the `$` is necessary (i.e. when checking whether we are looking at `command/cp` or `command/cp-DaisyChain`), and removed it where it was superfluous.

Fixes regex conflicts with CloudSDK detection

---

.gitmodules

Seems to be the source of a copybara error.

Remove unused submodule protorpc from .gitmodules.

---

gslib/commands/acl.py
gslib/commands/rsync.py

Backfill changes from CL 319998445 and CL 319797225:
-- Add a note about Cloud Powershell regex.
-- Update examples that use wildcards to be simpler.
-- Remove some uses of the future tense.

Docs updates

---

gslib/addlhelp/crc32c.py

Update instructions from Python 2 to Python 3 for the various Linux systems.
This backfills changes made in cl/324024380

Update crcmod install instructions

---

gslib/third_party/storage_apitools/storage_v1_messages.py

Update Apitools messages noncurrentTimeBefore and customTimeBefore fields.
Backend has changed to only accept dates not datetimes.
If a bucket is submitted with a full datetime string in RFC 3339 format, it can cause an error when Apitools tries to serialize or deserialize it.

Update Apitools messages noncurrentTimeBefore and customTimeBefore

---

.gitmodules
gsutil.py
setup.py

Proxy authentication is not working for python3.  b/161686363, https://github.com/GoogleCloudPlatform/gsutil/issues/1065 
The problem is because of socksipy-branch.
This PR remove the socksipy dependency and instead relies on the socks.py lib present in httplib2
Dependent on: https://github.com/GoogleCloudPlatform/gcs-oauth2-boto-plugin/pull/52
Requires httplib2>=0.18

Remove socksipy dependency to fix proxy authentication

---

gslib/__main__.py

`gsutil` can't really do much here so we display a message to ask users
to re-initialize credentials.

Handle SAML reauth challenge.

---

gslib/commands/compose.py
gslib/commands/config.py
gslib/commands/cp.py

Currently, this page indicates the maximum number of chunks is determined by MAX_COMPONENT_COUNT, but my understanding is the limit is actually determined by MAX_COMPOSE_ARITY.
I don't have a lot of experience changing code aspects of the gsutil repository, so please give this change extra scrutiny.

Change info about parallel composite upload chunks

---

gslib/addlhelp/encoding.py
gslib/addlhelp/versions.py
gslib/commands/cp.py
gslib/commands/iam.py
gslib/commands/rm.py
gslib/commands/rsync.py

This change backfills cl/333787211: The term overwrite doesn't have an exact meaning in our docs (and at times the use of the word is inconsistent with the actual behavior of GCS). Using "replace" instead should aid in reader comprehension easier and reduce confusion.

Scrub "overwrite" from the docs

---

gslib/commands/rsync.py

The second slash is needed in the -j example in order to convert correctly into cloud.google.com documentation

Code sample formatting fix

---

gslib/tests/test_rsync.py

With V4 signature, objects starting with a slash do not work. So skipping this test for S3.

Skip leftover dir placeholder test for S3

---

test/ci/kokoro/config_generator.sh
test/ci/kokoro/windows/config_generator.ps1

These credentials return a `401` error when used by themselves.
We only need the key file earlier in the config for authentication.

Remove unused credentials from Kokoro build.

---

gslib/gcs_json_api.py
gslib/tests/test_setmeta.py

Previously the JSON API would not delete the headers `cache-control`, `content-disposition`, `content-encoding`, and `content-language`.

Headers can now be removed

---

gslib/commands/config.py
gslib/context_config.py
gslib/tests/test_context_config.py

Sets up config files needed for mTLS.
Does not actually attempted to connect to mTLS endpoints yet.
Note: Since the context_config.py file hasn't been tested against a live backend, it will probably require tweaking later.
However, I think I got close to full unit test coverage. PEM parsing logic and tests were copied from gcloud, so I didn't look too deep into coverage there.

mTLS Part 1/2: Config Setup

---

gslib/commands/signurl.py

I think this will fix a generation issue when creating the c.g.c documentation, though we won't know for sure until the next generation run.

Add spacing to the signurl options table

---

.travis.yml

Travis CI for pypy fails with the following error
https://travis-ci.org/github/GoogleCloudPlatform/gsutil/jobs/741939544
```
RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.
```
As a quick solution, setting the env variable.

Add allow pypy installation by allowing openssl 1.0.2

---

gslib/tests/test_seek_ahead_thread.py
gslib/tests/test_ui.py

Use is_alive in favour of isAlive for Python 3.9 compatibility.

---

gslib/commands/rsync.py

This fixes below deprecation warnings : 
```
find . -iname '*.py' | xargs -P4 -I{} python3 -Wall -m py_compile {} 
./gslib/commands/rsync.py:112: DeprecationWarning: invalid escape sequence \.
""" + _SYNOPSIS + """
```

Fix deprecation warnings due to invalid escape sequences.

---

gslib/addlhelp/crc32c.py

It works without `sudo`. Did it 10 minutes ago.

no need of sudo to pip install crcmod on macOS

---

gslib/commands/iam.py

`json.dumps` will output trailing spaces after commas, if an indent is
specified. Explicity defining the separators, i.e., comma without a
space, fixes this.
Closes: https://github.com/GoogleCloudPlatform/gsutil/issues/975
Signed-off-by: Bart Smykla <bsmykla@vmware.com>

Prevent trailing spaces in json output of iam get

---

gslib/__main__.py
gslib/cloud_api_delegator.py
gslib/context_config.py
gslib/gcs_json_api.py
gslib/tests/test_boto_util.py
gslib/tests/test_cloud_api_delegator.py
gslib/tests/test_context_config.py
gslib/tests/test_gcs_json_api.py
gslib/utils/boto_util.py

Configure gsutil to optionally connect to the mTLS endpoint, using a device certificate.
Sets up an E2E test to automatically confirm this authentication type continues working.
Builds on: https://github.com/GoogleCloudPlatform/gsutil/pull/1115
Next: https://github.com/GoogleCloudPlatform/gsutil/pull/1142

mTLS Part 2/3: Connect to Endpoint

---

gslib/context_config.py

Fix Python 3 string decoding for mTLS cert generation.

mTLS Part 2.1/3: Python 3 cert decoding fix

---

gslib/commands/cp.py

The generation pipeline to cloud.google.com is rendering this section incorrectly. I *think* it's because there's an extra space for some of these lines, but won't know for sure until the next release. Rendering fixed in the c.g.c docs in cl/343521790.

Format fix for cp.py

---

gslib/commands/cp.py

These fixes should improve doc generation to cloud.google.com

Small format fixes to cp.py

---

gslib/commands/cp.py

Add a note about using -n to avoid re-uploading during bulk resumable uploads.

Backfill CL 346112758

---

gslib/commands/cors.py

This ensures that a code block is generated in https://cloud.google.com/storage/docs/gsutil/commands/cors?hl=en

Fix formatting for empty CORS JSON document

---

gslib/gcs_json_api.py

The error message from the xml apis already contains the information I added here, and gsutil already displays it in full:
```
ServiceException: 409 Bucket already exists.
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyExists</Code><Message>The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.</Message><BucketName>asdf</BucketName><RequestId>2CA9EED1F16E66BB</RequestId><HostId>Ai5MUQ9EG3tJq0ZmlNs9InwVP8DSd4Qnz7TzAMAPORUn/d92j5noMKDi/1/4bapX2+wb9LHwJ5E=</HostId></Error>
```
As a result, I only made this change for the gcs json API.

Improve error message when a bucket's name collides with another.

---

gslib/gcs_json_api.py

Trace token was being lost in the headers reset for resumable uploads.

Add perf-trace-token support for resumable uploads.

---

gslib/utils/copy_helper.py

A bug was filed where files downloaded using gsutil were not getting striped on a Lustre File System. It was brought to our notice that this happens because of the APPEND mode. Changing the append mode to r+b mode fixes this issue.

Open files in non-append mode to make stripe functionality work in Lustre file sytems

---

.github/workflows/ci.yml
test/ci/kokoro/linux/py38_json.cfg
test/ci/kokoro/linux/py38_xml.cfg
test/ci/kokoro/macos/py38_json.cfg
test/ci/kokoro/macos/py38_xml.cfg
test/ci/kokoro/run_integ_tests.sh
test/ci/kokoro/windows/py38_json.cfg
test/ci/kokoro/windows/py38_xml.cfg

Adds Python 3.8 checks to kokoro and github actions. I also had to edit the `run_integ_tests.sh` script to make sure that `pyenv update` was called before `pyenv install --list` to ensure that Python 3.8 was available.

Add CI checks for Python 3.8

---

gslib/commands/help.py

The gsutil help metadata command fails for Python2 if PAGER is set for the user's environment.

Fix UnicodeEncodeError in Python2 for help metadata command

---

gslib/addlhelp/subdirs.py

I don't believe the GCP Console uses this convention anymore, and it's causing user confusion.
This change backfills edits made to c.g.c docs in cl/345033621

Reduce discussion for _$folder$ behavior

---

gslib/commands/cp.py

Properly document the metadata settings on objects when using the `-z` flag.

Backfill CL 352809909

---

gslib/commands/ls.py
gslib/tests/test_ls.py
gslib/third_party/storage_apitools/storage_v1_messages.py

The new field, if present, would look like this:
```
$ gsutil ls -Lb gs://bucket/
gs://bucket/ :
Storage class:                  STANDARD
Location type:                  multi-region
Location constraint:            US
Versioning enabled:             None
Logging configuration:          None
Website configuration:          None
CORS configuration:             None
Lifecycle configuration:        None
Requester Pays enabled:         None
Labels:                         None
Default KMS key:                None
Time created:                   Wed, 16 Sep 2020 23:07:02 GMT
Time updated:                   Wed, 02 Dec 2020 22:45:24 GMT
Metageneration:                 4
Bucket Policy Only enabled:     False
Satisfies PZS:                  True
ACL:
```

Show satisifiesPZS info in bucket info listing (ls -Lb)

---

gslib/tests/test_cat.py
test/ci/kokoro/run_integ_tests.sh
test/ci/kokoro/windows/run_integ_tests.bat

Kokoro marks runs as failed when the exit code of run_integ_tests.sh is != 0. Since the exit code of a .sh file is the exit code of the last command if not otherwise specified, when we added mTLS checks to the end of the script we were hiding failures from other parts of the test suite.

Register integration test failures in kokoro script

---

gslib/tests/test_compose.py
gslib/tests/test_cp.py
gslib/tests/test_ls.py
gslib/tests/test_mv.py
gslib/tests/test_requester_pays.py
gslib/tests/test_rm.py
gslib/tests/test_rsync.py
gslib/tests/testcase/integration_testcase.py
gslib/tests/testcase/unit_testcase.py

Adding these functions to the test case as it's generally easier to track down when these functions are called if they're centralized.

Tests now use wrapper functions for object clone/set contents

---

gslib/commands/iam.py

Reverts GoogleCloudPlatform/gsutil#884
Removing temporary hack that was needed during upstream IAM API changes.

Revert "Removing version from set IAM policy for objects"

---

gslib/tests/test_cp.py
gslib/utils/copy_helper.py

Gsutil used to complete downloads in the following steps:
1. Download data to a temporary file.
2. Unlink any existing files at the final destination.
3. Rename the temporary file with the final file name.
This was a problem when two instances of gsutil were running, since they'd use the same name for the temporary destination file. This meant that after one instance completed steps 2 and 3, it'd remove the temporary file the second instance was writing to. As a result, instance 2 could find a file at the final destination and remove it in step 2, but would not have anything to rename with the final file name in step 3. This would make it look like no data was transferred.
This PR removes the unlink operation in step 2, which potentially introduces other problems, since the `os.rename` …

Improve reliability when multiple instances of gsutil transfer to the same destination

---

gslib/commands/notification.py

Update reference docs to note that notifications can overlap in a bucket

Backfill cl/363031725

---

gslib/addlhelp/versions.py

The c.g.c. generator doesn't look like it parses this correctly. Instead of trying to post-process this or modify the generator, I think we should take the easy way out and simply remove the code block.

Remove code block from within link block

---

gslib/commands/config.py
gslib/utils/copy_helper.py

The cp operation attempts to use compose to upload large objects.
_ShouldDoParallelUpload determines if the user request meets the
criterion necessary for this optimization.
Compose API did not support composition of KMS-encrypted objects, which
will soon be added.
'GSUtil:disable_parallel_composite_upload_kms_check' removes KMS verification
when set to True.

CopyHelper accepts kms check bypass.

---

gslib/gcs_json_api.py
gslib/tests/test_copy_helper_funcs.py

StreamExhausted handling is broken currently because it tries to access the `message` member on the error object which does not exist. 
I have also added a message to try cleaning up tracker files if the issue persists.
For context b/144166902

Fix StreamExhausted Error handling for Resumable uploads

---

test/ci/kokoro/run_integ_tests.sh

Looks like Kokoro on macOS has been failing since quite a while. Looking at one such failure, the issue seems to be happening because of `brew install pyenv` failure.  https://fusion2.corp.google.com/invocations/bf191791-bdaf-4335-b997-515a4b92b73f/targets/cloud_storage_gsutil%2Fmacos%2Fpy37_json/log
I am trying to run `brew update` before the `brew install pyenv` command.

Fix kokoro failures on MacOS

---

gslib/commands/setmeta.py
gslib/tests/test_setmeta.py

Without headers, the command just iterates over the objects it matches and doesn't do anything.

Raise error in setmeta if no headers are provided.

---

gslib/tests/test_cp.py
gslib/tests/util.py

Some tests weren't working as intended because progress callbacks are called less frequently than they assumed. See the conditions [here](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/progress_callback.py#L128).

Fix resumable upload tests

---

gslib/command.py
gslib/tests/test_parallelism_framework.py

The existing code was still resulting in connections being reused across processes. Overwriting the state used to track them with default values works as expected.

Delete connections after fork.

---

gslib/daisy_chain_wrapper.py
gslib/tests/test_daisy_chain_wrapper.py

The Daisy chain copy for GCS to S3 is broken on windows because of different read and write size which happens as Windows uses 64KB TRANSFER_BUFFER_SIZE as of https://github.com/GoogleCloudPlatform/gsutil/commit/ffa1eb7d4d9fe8dd877452f28f55fdf51c2a6c12 and the daisy chain logic expects same read and write size. However, the http.client module will read in 8KiB chunks. 
This PR modifies the read logic so that a read size < TRANSFER_BUFFER_SIZE can be handled.
For reference: b/185961088

Fix daisy chain for windows

---

gslib/tests/test_psc.py
test/ci/kokoro/run_integ_tests.sh
test/ci/kokoro/windows/run_integ_tests.bat
test/ci/kokoro/windows/run_integ_tests.ps1

Confirms custom endpoints are maintained through sliced downloads and parallel composite uploads by testing compatibility with private service connect (PSC).

E2E Tests for Persisting Custom Endpoints

---

gslib/gcs_json_api.py
gslib/tests/test_compose.py
gslib/tests/test_cp.py
gslib/utils/copy_helper.py

gsutil will now be able to use compose to parallel upload large objects.

Removed kms check when determining if cp should do a parallel upload.

---

gslib/tests/test_copy_helper_funcs.py
gslib/utils/copy_helper.py

Along with a [boto PR](https://github.com/gsutil-mirrors/boto/commit/fe0a6a99a7e2a89714c91ce91e827a9d85e3acc9), this provides a workaround for #1249.

Support skipping integrity checks in daisy chain transfers.

---

gslib/tests/test_compose.py

One compose objects test should have been skipped for s3, and we needed to release a new version of apitools, which the repo now points to.

Fix failing tests for release.

---

gslib/commands/cp.py

The examples for -D option is confusing, as -p option is also specified. 
Some users end up thinking that these two options should be used together. This is not always the case (e.g. for bucket with uniform bucket-level access),  and an error will be returned in case OWNER permission is missing as OWNER permission is required for preserving ACLs. 
This cl provides additional clarifications to avoid further support tickets.

Specify the purpose of -p option for -D example

---

gslib/tests/test_cp.py
gslib/utils/copy_helper.py

Fixes https://github.com/GoogleCloudPlatform/gsutil/issues/800
Raising an error now if destination ends with a delimiter.

Raise error for invalid destination.

---

test/ci/kokoro/run_integ_tests.sh

Our Kokoro job has been failing for Linux only.
This started happening since May 07
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:cloud_storage_gsutil%2Flinux%2Fcontinuous
Looking at the log, it seems it is running all the tests but in the end failing because of errors like these:
```
protocol version mismatch -- is your shell clean?
(see the rsync man page for an explanation)
rsync error: protocol incompatibility (code 2) at compat.c(178) [Receiver=3.1.3]
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
```
Check b/187701234#comment12 for more info.

Fix kokoro failures on linux because of pyenv

---

gslib/commands/help.py

`-o`/`--option` takes a single mandatory parameter of a fixed form and this should be clear in the help
`-o` flags can be included more than once (as with `-h`).
Fixes #1270

Fix gsutil help for -o

---

gslib/tests/test_rm.py

Rm tests are occasionally failing because the backend gives two different messages.
```
gsutil -h x-goog-if-generation-match:12345 rm gs://gsutil_test_bucket-4/t
est.txt
Removing gs://gsutil_test_bucket-4/test.txt...
PreconditionException: 412 At least one of the pre-conditions you specified did not hold.
```
and
```
$ gsutil -h x-goog-if-generation-match:12345 rm gs://gsutil_test_bucket-4/test.txt
Removing gs://gsutil_test_bucket-4/test.txt...
PreconditionException: 412 Precondition Failed
```
Making the test less strict so that it can work for both the messages.

Fix flaky test for rm using preconditions

---

gslib/iamcredentials_api.py

We were getting a raising-bad-type error in the modified file because we were raising the output of a function with no return value: _TranslateExceptionAndRaise. Technically there's nothing wrong with this since the statement  `raise _TranslateExceptionAndRaise(...)` would never be fully evaluated since _TranslateExceptionAndRaise raises an error, but removing the extraneous `raise`s is cleaner, so I did that instead of disabling the check.

Fix raising-bad-type yapf errors.

---

gslib/context_config.py
gslib/tests/test_context_config.py

- The certificate discovery has the following logic:
- Use the user specified command in `.boto` file if available
- Otherwise, automatically locate the SecureConnectHelper Metadata JSON
Notes: This PR is backwards-compatible
For more information about the mTLS spec please read: [AIP-4114](https://google.aip.dev/auth/4114)

Onboard mTLS support with AIP-4114 for gsutil

---

gslib/addlhelp/crc32c.py
gslib/commands/pap.py

* Update text for `gsutil pap`.
* Remove some text from the Windows instructions for crcmod.

Backfill some changes to the help docs

---

gslib/context_config.py
gslib/tests/test_context_config.py
gslib/tests/test_execution_util.py
gslib/tests/test_temporary_file_util.py
gslib/utils/copy_helper.py
gslib/utils/execution_util.py
gslib/utils/temporary_file_util.py

Make temporary file naming utils generic.
Make binary running logic generic.
Fix an issue where unit tests fail if `cert_provider_command` is present in `.boto`.

Make certain utils generic for future projects

---

gslib/context_config.py
gslib/tests/test_context_config.py

Inconsistencies have arisen!
There's debate about whether we should be using snake case or camel case, but, regardless, we should be uniform in a single file.

Remove mTLS in-file naming inconsistencies (snake case vs camel case)

---

gslib/commands/ls.py
gslib/tests/test_ls.py
gslib/utils/ls_helper.py

Manually tested S3 since unit test covers GCS JSON:
```
$ python3 ./gsutil mb s3://12versiontest34
Creating s3://12versiontest34/...
$ python3 ./gsutil versioning set on s3://12versiontest34
$ python3 ./gsutil cp ~/Desktop/foo1 s3://12versiontest34                                           
$ python3 ./gsutil cp ~/Desktop/foo1 s3://12versiontest34                                            
$ python3 ./gsutil ls -a s3://12versiontest34
s3://12versiontest34/foo1#t3kEY8Yx8mu8xp4PAJB00_HfFZg16Rso
s3://12versiontest34/foo1#S7jkzG1up8Ory1Cdkv8SDzfpe2tImBL3
$ python3 ./gsutil ls -a s3://12versiontest34/foo1#S7jkzG1up8Ory1Cdkv8SDzfpe2tImBL3
s3://12versiontest34/foo1#S7jkzG1up8Ory1Cdkv8SDzfpe2tImBL3
```
Before:
```
$ python3 ./gsutil ls -a …
```

Support generation querying for ls command.

---

gslib/commands/compose.py
gslib/tests/test_compose.py

Fixes issue where gzip encoding isn't getting copied, losing automatic unzipping behavior.

Copy Content-Encoding from first object in compose command.

---

gslib/__main__.py
gslib/command_runner.py
gslib/commands/update.py
gslib/tests/test_command_runner.py
gslib/tests/test_update.py
gslib/utils/constants.py
gslib/utils/update_util.py

This PR does the following:
- Alerts users running the `upgrade` or `version` command that they should install Py3 to stay up to date with the latest code. This way if you can't use the `upgrade` command, there will still be messaging.
- Python 2 gets a different upgrade tarball, leaving the door open for releasing bug fixes later on.

Adds a message encouraging py3 upgrade

---

gslib/commands/config.py
gslib/commands/cp.py
gslib/tests/test_stet_cp.py

Disabling STET features temporarily. This PR should be reverted for gsutil 5.x

Disable STET feature temporarily

---

.github/workflows/ci.yml
gslib/utils/version_check.py
gsutil

- Bump gcs-oauth2-boto-plugin version to 3.0
- Remove Python 2.7 from CI
- Remove Python 2.7 from version_check.py
- Set the `gsutil` shebang to pick Python 3

Bump gcs-oauth2-boto-plugin version to 3.0

---

gslib/commands/mb.py
gslib/commands/rpo.py
gslib/tests/test_rpo.py

Before
```
python3 gsutil.py rpo set Default gs://dpednekar-rpo-test-1
Setting rpo DEFAULT for gs://dpednekar-rpo-test-1
```
After:
```
$ python3 gsutil.py rpo set Default gs://dpednekar-rpo-test-1
CommandException: Invalid value for rpo set. Should be one of (ASYNC_TURBO|DEFAULT)
$ python3 gsutil.py mb -l nam4 --rpo Default gs://dpednekar-rpo-test-3
CommandException: Invalid value for --rpo. Must be one of: (ASYNC_TURBO|DEFAULT), provided: Default
```

Do not upper case rpo values

---

gslib/tests/test_context_config.py
gslib/tests/test_execution_util.py
gslib/tests/test_hashing_helper.py
gslib/tests/test_kms.py
gslib/tests/test_parallelism_framework.py
gslib/tests/test_stet_util.py

Pipinstall tests for the release process started to fail because a change was introduced where mock library gets installed conditionally only for python2 https://github.com/GoogleCloudPlatform/gsutil/commit/043abe9b58ff2aff52325abeebde54cd056c0c3f  but some tests were still importing mock directly.
Not using six because this branch is meant to only support python3 going forward.

Replace invalid import mock statements

---

gslib/commands/hash.py
gslib/commands/mb.py
gslib/commands/rb.py

Small updates to gsutil help docs
-- Make it clearer that `hash`, `mb`, and `rb` commands can apply to more than one resource.
-- Cut out excessive text from the `mb` command, and move useful information into the "options" section.

Backfill changes made in cl/397806013

---

gslib/tests/test_iam.py
gslib/utils/iam_helper.py

Currently we don't allow assigning roles to these groups, but we should be able to remove roles from these groups. You can, currently, with `iam set` but not with `iam ch`.

Allow the removal of project convenience groups.

---

gslib/utils/copy_helper.py

This fixes https://github.com/GoogleCloudPlatform/gsutil/issues/950 by closing the upload stream before we try to unlink the temp gzip file.

Close upload stream before we try to unlink temp file

---

gslib/tests/testcase/integration_testcase.py

These values have been changed to a standard test account controlled internally.

Changing test email and user references to safer values.

---

gslib/commands/pap.py
gslib/tests/test_ls.py
gslib/tests/test_mb.py
gslib/tests/test_pap.py

For some time the backend might return `unspecified` or `inherited` for the test project. We will change everything to inherited once the backend rollout is done.

PAP: Temporarily handle unspecified as well as inherited

---

gslib/tests/test_storage_url.py

Previously some environments were coming back with a rather obscure error:
```
======================================================================
ERROR: FailedTest (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: FailedTest
Traceback (most recent call last):
File "/usr/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
module = __import__(module_name)
ModuleNotFoundError: No module named 'FailedTest'
```

Fixes broken import in test_storage_url

---

gslib/commands/pap.py
gslib/tests/test_ls.py
gslib/tests/test_mb.py
gslib/tests/test_pap.py

* PAP: Temporarily handle unspecified as well as inherited returned by the backend
* Fix mb and ls tests
* Fix pap tests
* Fix mb test
(cherry picked from commit b229b673aad1eaf324a69bd44c02eb9b03b500a4)

PAP: Temporarily handle unspecified as well as inherited (#1404)

---

gslib/addlhelp/creds.py

The current styling ("for more information, see: <indent>") is bolding all the links in https://cloud.google.com/storage/docs/gsutil/addlhelp/CredentialTypesSupportingVariousUseCases. These edits fix that. See https://docs.google.com/spreadsheets/d/13Efj5QRmQnW-HFClhLQRXeFjm50q5lMfUWf_9AvGcrw/edit?resourcekey=0-c5be_LssNOdmhHBFzqTMkg#gid=0 for more information.

Fix bug in docs rendering

---

gslib/commands/mv.py

Docs work described in here: https://b.corp.google.com/issues/202778546, https://critique-ng.corp.google.com/cl/403993699

Updating link to cp Options docs

---

gslib/command.py
gslib/command_runner.py
gslib/commands/cp.py
gslib/tests/test_command.py
gslib/tests/test_shim_util.py
gslib/utils/shim_util.py

This PR does the following:
- Translates the gsutil command to it's gcloud storage equivalent if it was requested by the user.
- Runs the gcloud storage command if successfully translated.

Part 2 of shim for running gcloud storage: Invoke gcloud storage command

---

gslib/__main__.py

See b/208418444#comment7 for details.
We are adding a dummy import so that the module gets loaded before the any multiprocessing steps are executed.

Import shim before multiprocessing manager is activated

---

gslib/__main__.py
gslib/command.py
gslib/command_runner.py
gslib/commands/cp.py
gslib/tests/test_shim_util.py
gslib/utils/shim_util.py

Reverting https://github.com/GoogleCloudPlatform/gsutil/pull/1437 and https://github.com/GoogleCloudPlatform/gsutil/pull/1436
The shim related changes were temporarily removed because the Gcloud GCE release tests were failing. I am rolling out a fix for the release infrastructure that takes care of this issue. It is now safe to re-introduce the shim-related changees.

Bring back shim 

---

.gitmodules

Git Actions CI started breaking with https://github.com/GoogleCloudPlatform/gsutil/runs/4779653292?check_suite_focus=true
As per the link in the error message, this is happening because github is no longer supporting unauthenticated git protocol. This only affects git:// and not https://

Replace git with https in .gitmodules

---

gslib/commands/mv.py
gslib/commands/perfdiag.py
gslib/commands/rsync.py

Several links were added with incorrect styling, which affects content generation into cloud.google.com documentation

Fix linking syntax in help docs

---

gslib/commands/mb.py
gslib/commands/pap.py
gslib/tests/test_mb.py
gslib/tests/test_pap.py

Now that inherited is supported and public, we can replace unspecified with inherited.

PAP: Replace unspecified with inherited

---

gslib/commands/rm.py

Add a use case for how to delete all objects in a bucket without deleting the bucket itself.

Docs: Use case for deleting objects, not bucket

---

gslib/tests/test_cp.py
gslib/tests/test_ls.py

A couple of tests introduced in https://github.com/GoogleCloudPlatform/gsutil/pull/1448 are breaking on windows. This PR fixes them.

Fix shim tests for windows

---

gslib/commands/rm.py

The info (previously on the Best Practices doc) is now moved to a new doc. Updating the link here to point to that doc.

Docs: Update a link

---

gslib/tests/test_cp.py
gslib/tests/test_ls.py
gslib/tests/test_rm.py
gslib/tests/test_shim_util.py
gslib/tests/testcase/integration_testcase.py
gslib/utils/shim_util.py

Updating the `use_gcloud_storage` boto config option to just accept either `True` or `False` values.
Before:
```
use_gcloud_storage = if_available_else_skip/never/always/dry_run
```
After:
```
use_gcloud_storage=True/False
```
If you set `use_gcloud_storage=True`, it will try to run `gcloud storage` and will fallback to running gsutil if a command/flag is not yet supported via the shim or gcloud storage. This is equivalent to setting `if_available_else_skip` before.
Introduced a hidden config option `hidden_shim_mode` that should be used only for debugging and testing purposes.
For `always` equivalent, `hidden_shim_mode=no_fallback` can be used, which will raise an error if the requested command/flag is not supported via the shim.
Similarly, to run the command in dry_run mode, …

Shim: Make use_gcloud_storage accept boolean values instead of strings

---

gslib/command.py
gslib/commands/cp.py
gslib/commands/rsync.py
gslib/name_expansion.py
gslib/storage_url.py
gslib/tests/test_copy_objects_iterator.py
gslib/tests/test_cp.py
gslib/tests/test_mv.py
gslib/tests/test_naming.py
gslib/utils/copy_helper.py

Applies to mv logic as well. Basically treats destination as an existing
directory if multiple top-level sources are detected.

Fix copying duplicate file name conflicts.

---

gslib/commands/ls.py
gslib/commands/mb.py
gslib/tests/test_ls.py
gslib/tests/test_mb.py

The --placement flag  and the PlacementConfig support will be dropped. Dual regions can be now specified via the location `-l` flag.

Custom dual region - Drop placement flag as multiple locations can now be provided via -l flag

---

gslib/tests/test_wrapped_credentials.py
gslib/utils/wrapped_credentials.py

This error gets raised when the credentials are Workforce Pool 
credentials with Service Account Impersonation

Include TypeError as a valid exception for aws.Credentials construction

---

gslib/commands/cp.py

There's a few places where spacing is causing normal text to get rendered as code in the generated online help docs

Fix spacing in help doc

---

gslib/addlhelp/dev.py

The linter command does not format correctly on cloud.google.com, and while PR #1281 attempted to fix this, it appears it did not. My guess is the indentation issue is related to the entire item being indented an extra space (owing to it being a 2-digit number). To circumvent this, I'm proposing we combine two separate-but-related items above into a single item.

Fix formatting issue in help docs

---

gslib/tests/test_cat.py
gslib/utils/cat_helper.py

The gsutil cat -h flag when used on multiple objects which are small, first prints the headers of all the objects the user entered and then prints the contents of all the objects the user entered.
The reason the gsutil cat -h command with multiple small files does not work properly is because the headers are written to stderr whereas the object contents are written to stdout. Since stderr does not have a buffer and stdout does, with small files, the buffer is not cleared fast enough and both headers are printed before the first content is printed. By flushing the buffer immediately, the header of the first object is printed followed by the content, header of the second object followed by the content, etc..

Added flush to cat_helper.py

---

gslib/tests/test_parallelism_framework.py

`threading.currentThread` was deprecated in Python 3.10 (October 2021).
Replace with `threading.current_thread`, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
(Also remove the redundant parentheses.)

Replace deprecated threading.currentThread with current_thread

---

gslib/commands/ls.py
gslib/commands/mb.py
gslib/tests/test_ls.py
gslib/tests/test_mb.py

Reverts GoogleCloudPlatform/gsutil#1480 and keeps some of the modifications to the -l flag for mb.

Bring back placement flag for custom dual regions

---

gslib/commands/cat.py
gslib/tests/test_cat.py
gslib/utils/cat_helper.py

Under the old cat command, if the user entered a gsutil cat -r x-y gs://object and the starting range is out of bounds, an error was thrown. Under the new behavior, nothing is outputted and no error is thrown, just like Python's behavior.
Additionally, under the old gsutil cat code, when a user entered `gsutil cat -r - gs://object' a "CommandException" was thrown. Under the new code, the whole object is printed, just like Python's default behavior.

Updated the cat -r command error behavior

---

gslib/commands/cat.py
gslib/tests/test_cat.py
gslib/utils/shim_util.py

Before, there was no shim support for the cat command.
After, there is now shim support and the gsutil cat tests ensure the
gcloud command passes them.

Added shim support for cat

---

gslib/commands/kms.py
gslib/commands/web.py
gslib/tests/test_shim_util.py
gslib/tests/test_web.py
gslib/utils/shim_util.py

Removes custom shimming through global constants because they result in test flakes.

Shim web command

---

gslib/tests/test_copy_helper_funcs.py
gslib/tests/test_cp.py
gslib/tests/test_web.py
gslib/utils/copy_helper.py

Before, chunks were being uploaded as the default storage class.
After, chunks are being uploaded as the custom storage class.

Allow custom storage class flag for PCU

---

gslib/tests/test_cp.py

Gcloud and Gsutil have a different number of whitespaces between
`Storage Class:` and the type of storage class. Edited test accordingly.

Edit test_nearline_applied_to_parallel_composite_upload so shim passes.

---

gslib/commands/setmeta.py
gslib/tests/test_setmeta.py
gslib/tests/test_shim_util.py
gslib/utils/shim_util.py

Found some bugs related to flag translation: (1) empty `headers` dict treated as `None`, (2) alternate precondition flags not supported, and (3) capitalization not preserved for custom keys.

Shim setmeta

---

gslib/tests/test_wrapped_credentials.py
gslib/utils/wrapped_credentials.py

This allows executable-sourced external account credentials, and 
configurable token lifespans for service account impersonation

Update google auth dependency

---

gslib/addlhelp/creds.py
gslib/addlhelp/security.py
gslib/commands/config.py

Remove discussion of installing stand-alone versions of gsutil. In the config.py help doc, call stand-alone gsutil "legacy"

Backfill cl/471889749

---

test/ci/kokoro/run_integ_tests.sh
test/ci/kokoro/windows/run_integ_tests.bat

We haven't gotten new mTLS test project credentials after asking, and the test failures have been making debugging harder.

Disable mTLS E2E tests

---

gslib/commands/rsync.py
gslib/tests/test_rsync.py
gslib/tests/test_wildcard_iterator.py

The test I edited tested a regex pattern that was in the docs, so I made sure the regex worked on both Windows and non-Windows systems.

Fixed rsync -x test for Windows and updated docs to match

---

gslib/commands/lifecycle.py
gslib/tests/test_lifecycle.py

Shimmed "get" subcommand output should be similar to gsutil, except for the case where the lifecycle doesn't exist. In that case, the shim will print "null" or a mostly empty JSON object instead of "%s has no lifecycle configuration.\n".
Do not submit until corresponding gcloud CLs are in to support the lifecycle file format.

Shim lifecycle command.

---

.github/workflows/ci.yml
gslib/tests/testcase/unit_testcase.py

CI now pins Ubuntu to `20.04` as per https://github.com/actions/setup-python/issues/541
Also adding support for `3.10` and `3.11` since it's officially out of alpha.

Small CI fix

---

gslib/addlhelp/creds.py

This fix updates the service accounts link as the current compute/docs/authentication redirect link is being updated to follow the new authentication template and would break this reference point. Also fixes a few descriptions and product name for Compute Engine.

 Update the service accounts links

---

setup.py

Tested on my virtual env
```
$ pip freeze | grep httplib2
$ pip install .
$ pip freeze | grep httplib2
httplib2==0.20.4
```

Pin httplib2 to 0.20.4 version

---

gslib/tests/test_rsync.py

The test was failing on windows because of path separator mismatch.

Fix rsync -x test for windows

---

gslib/commands/mb.py
gslib/tests/test_mb.py

The mb tests have been modified so that they pass with the shim turned on, and I also fixed a few tests not related to CDR.

Adding shim support for custom dual regions

---

gslib/commands/acl.py
gslib/gcs_json_api.py
gslib/tests/test_acl.py
gslib/tests/test_storage_url.py

Running tests via gcloud storage revealed a few issues.
These are all the fixes I could make without stripping the extra ACL object fields gcloud storage displays. Mostly just translating XML to JSON predefined ACLs.
Lots of lines edited by the yapf formatter.

ACL command shim fixes for test parity.

---

gslib/tests/test_rpo.py

- Fix test_s3_fails_for_set test when it is running with shim mode enabled

fix e2e rpo set test for s3

---

gslib/commands/cp.py
gslib/commands/rsync.py
gslib/tests/test_copy_helper_funcs.py
gslib/tests/test_cp.py
gslib/tests/test_rsync.py
gslib/utils/copy_helper.py

Should address #1639 by performing at least one API call in the main process. 
Some uploads do not interact with the destination API until the transfer call itself, which must happen in child processes if parallelism is enabled. For users with reauth enabled, this results in a poor experience, since reauth challenges cannot be answered if they're triggered in child processes. This PR adds an API call in the main process to trigger the reauth flow for those users.

Handle reauth challenges gracefully in transfer commands.

---

gslib/commands/config.py

Here's what the new OAuth2 flow will look like:
```
$ gsutil config
This command will create a boto config file at
/home/thomasmaclean/.boto containing your credentials, based on your
responses to the following questions.
********************************************************
WARNING: The following authentication flow will fail on
or after Febuary 1 2023. Tokens generated before this
date will continue to work. To authenticate with your
user after this date, install gsutil via Cloud SDK and
run "gcloud auth login"
********************************************************
Please navigate your browser to the following URL:
https://accounts.google.com/o/oauth2/auth...
In your browser you should see a page that requests you to authorize access to Google Cloud Platform APIs and Services on …
```

Adding a warning about the deprecation of the OAuth2 flow.

---

gslib/commands/rpo.py
gslib/tests/test_rpo.py

There is a failing test for rpo command:  [test](https://github.com/GoogleCloudPlatform/gsutil/blob/a238e7e3500461dcd8ab15fcb6e7523a2b0f1e51/gslib/tests/test_rpo.py#L238)
The problem is that the [shimming_command_for_rpo_get](https://github.com/GoogleCloudPlatform/gsutil/blob/a238e7e3500461dcd8ab15fcb6e7523a2b0f1e51/gslib/commands/rpo.py#L86) crashes when an s3 bucket is passed due to `sub`  [transform_function](https://cloud.google.com/sdk/gcloud/reference/topic/projections) is expecting a string value, but instead is getting a `None` value, this PR fixes this issue by replacing the `sub` function for the `format` function

Fix rpo get shimming command

---

gslib/commands/acl.py
gslib/commands/autoclass.py
gslib/commands/cors.py
gslib/commands/defacl.py
gslib/commands/defstorageclass.py
gslib/commands/kms.py
gslib/commands/label.py
gslib/commands/lifecycle.py
gslib/commands/logging.py
gslib/commands/notification.py
gslib/commands/pap.py
gslib/commands/retention.py
gslib/commands/rpo.py
gslib/commands/ubla.py
gslib/commands/versioning.py
gslib/commands/web.py
gslib/tests/test_acl.py
gslib/tests/test_defacl.py
gslib/tests/test_kms.py
gslib/tests/test_lifecycle.py
gslib/tests/test_rpo.py
gslib/tests/test_web.py

This will fetch raw metadata, avoiding breaks in the keys the shim format strings are based on while gcloud transitions to standardized display formats.
Do not push until `--raw` flag is in gcloud storage. EDIT: It is time.

Add --raw flag to shim commands calling "describe" or "list".

---

gslib/__main__.py
gslib/tests/test_gsutil.py

gsutil does not handle OAuthException's from google-auth, which results in the entire stack trace being printed when an error occurs when using external account credentials. We should prompt the user to sign-in again in this case.

Handles OAuthException from google-auth

---

gslib/addlhelp/crc32c.py
gslib/commands/cp.py
gslib/commands/rsync.py

Streamline gsutil reference documentation coverage of checksum validation. Backfills cl/508132270 and cl/510034489.

Checksum streamlining in help docs

---

gslib/tests/test_boto_util.py
gslib/tests/test_data/test_external_account_authorized_user_credentials.json
gslib/tests/test_gcs_json_credentials.py
gslib/utils/boto_util.py

Fix error handling for the new external account authorized user credential type and added tests.
The external account authorized user credential type was added previously in #1617 but the type was missed in hasConfiguredCredentials. This results in the CLI returning misleading error messages when a failure occurs when using the new type.

Fix error message for external account authorized user credentials

---

gslib/tests/test_wrapped_credentials.py
gslib/utils/wrapped_credentials.py

Changing wrapped_credentials to store the client_secret and refresh_token from external account authorized user credentials. External account credentials did not have these fields so they were never added to wrapped credentials in the previous implementation. This led to a caching bug where the library did not recognize a newer version of the external account authorized user credential since the caching key did not include the refresh token.

Fix external_account_authorized_user implementation in wrapped_credentials.py + update google-auth dependency

---

gslib/commands/config.py

This check still fails if you run the command from gcloud, so this check just hides the explanatory error message.
There are three paths to the failure:
* Run `gsutil config` independently with OAuth creds (which is the default creds type) -> Then you get the gsutil explanatory error message and the failing code.
* Run `gsutil config` via gcloud with the `pass_credentials_to_gsutil=True` -> Gcloud intercepts and raises an error with a  gcloud explanatory message before gsutil runs.
* Run `gsutil config` via gcloud with the `pass_credentials_to_gsutil=False` -> You get the failing gsutil code without the gsutil explanatory error message. That is what this CL fixes.
Updates: https://github.com/GoogleCloudPlatform/gsutil/pull/1658

Removes the run-by-gcloud check from the broken OAuth (OOB) flow.

---

gslib/addlhelp/command_opts.py

Update the example associated with the -o flag to be gsutil-specific.

Backfill cl/521004072

---

test/ci/kokoro/run_integ_tests.sh

See https://github.com/pyenv/pyenv/wiki/Common-build-problems#2-your-openssl-version-is-incompatible-with-the-python-version-youre-trying-to-install

Fix SSL missing error by updating Linux Python 3.5 version.

---

gslib/context_config.py
gslib/tests/test_context_config.py
gslib/tests/test_gcs_json_credentials.py
gslib/tests/test_rpo.py
gslib/tests/test_wrapped_credentials.py
gslib/utils/boto_util.py
gslib/utils/system_util.py
gslib/utils/wrapped_credentials.py

Temporary certificate files used to be in the gsutil install directory. Now they're in the directory that contains the tracker file directory, which is controlled by the `state_dir` boto config option. Addresses #1517.
It looks like a recent PR didn't run the formatter, so there's some noise in this PR. The novel changes are in `context_config.py` and `test_context_config.py`.

Change state directory for mTLS.

---

gslib/tests/testcase/integration_testcase.py

S3 equivalents of PAP and UBLA got enabled for our test project, which caused some tests to fail. This PR introduces some code to respect settings for PAP and UBLA passed to the CreateBucket helper method for S3, which parallels the approach we took for the GCS APIs.
Since these features aren't supported by gsutil, I had to use some low(-er) level boto methods to disable them.

Respect PAP and UBLA settings in S3 tests.

---

test/ci/kokoro/run_integ_tests.sh
test/ci/kokoro/run_integ_tests_helper.sh

Post docker migration, the test script runs as root user which causes certain tests to fail that rely on posix behavior for non-root user. As a fix, I'm creating a new user from a parent script and calling the child script as the new user.
The kokoro failure for Linux  3.8 seems to be a flake that I was able to reproduce even without this fix. So I think there is something else going on there and I have a separate bug to investigate it: b/283171722

Fix test failures on linux after docker migration

---

gslib/cloud_api_delegator.py
gslib/tests/test_boto_util.py
gslib/tests/test_context_config.py
gslib/tests/test_shim_util.py
gslib/utils/boto_util.py
gslib/utils/shim_util.py

This will apply HMAC credentials to gcloud storage when appropriate. When supplied to gcloud storage, the HMAC credentials take precedence, so the shim needs to include gsutil's prioritization logic when applying those credentials. This PR encapsulates that prioritization logic in `boto_util.UsingGsHmac()` and applies it in both `cloud_api_delegator` and `shim_util`.

Adding support for HMAC auth to the shim.

---

gslib/tests/test_rewrite.py

The tests mentioned in the bug are 
```
gslib.tests.test_rewrite.TestRewrite.test_parallel_rewrite_bucket_flat_wildcard
gslib.tests.test_cp.TestCp.test_gzip_transport_encoded_parallel_upload_resumable
```
I couldn't reproduce flakes regarding the second test, and the bug does not contain a sponge log or details for it. Therefore, I'm ignoring it for now.
For the first test, I'm not certain why this PR works. I theorize something about the encryption key text does not interact well with the conversion from ASCII (with `.encode`) to Unicode (from `RunGsUtil`).
There are some mentions of encoding in the Python 3.8 change log that may explain why this issue affects 3.8 only.
https://docs.python.org/3/whatsnew/3.8.html
I also saw this in the 3.9 changelog, which might explain why the issue was …

Fix Python 3.8 Unicode error in test

---

gslib/commands/logging.py
gslib/commands/rsync.py

Slash escaping is in place to workaround how the documentation generator works, but it means examples presented in the command line help are incorrect.
The plan is to remove the escaping here in source and hope we remember to manually catch generator behavior in the remaining few gsutil releases.
This PR also fixes a minor formatting error in the logging help doc that was discovered in most recent doc generation run

Fix formatting behavior in rsync and logging help text

---

gslib/addlhelp/creds.py
gslib/commands/acl.py
gslib/commands/cp.py
gslib/commands/defacl.py
gslib/commands/rsync.py

Use "predefined" instead. Backfills cl/547282202.

Replace instances of "canned"

---

gslib/commands/bucketpolicyonly.py
gslib/commands/hmac.py

- Adds tabs to hmac get shim output string to make it match gsutil.
- Fixes shim output string for bucketpolicyonly get command so it maches gsutil.

Shim output formatting fixes for hmac and bpo

---

gslib/addlhelp/command_opts.py
gslib/addlhelp/creds.py
gslib/commands/logging.py
gslib/commands/mb.py
gslib/commands/rpo.py
gslib/commands/setmeta.py
gslib/commands/signurl.py

The need for these changes surfaced during the latest generation of the gsutil reference documentation

Backfill help text changes

---

gslib/addlhelp/shim.py
gslib/tests/test_ls.py

Also updating the shim.py page to highlight the space vs tabs differences.

Minor change to default event based hold test for parity

---

gslib/addlhelp/command_opts.py

Provide a bit more clarity regarding the behavior of the -o global flag

Backfill cl/543496942

---

gslib/tests/test_acl.py
gslib/tests/test_autoclass.py
gslib/tests/test_cat.py
gslib/tests/test_copy_objects_iterator.py
gslib/tests/test_cp.py
gslib/tests/test_defacl.py
gslib/tests/test_hash.py
gslib/tests/test_hmac.py
gslib/tests/test_iam.py
gslib/tests/test_kms.py
gslib/tests/test_lifecycle.py
gslib/tests/test_ls.py
gslib/tests/test_mb.py
gslib/tests/test_mv.py
gslib/tests/test_retention.py
gslib/tests/test_retention_util.py
gslib/tests/test_rm.py
gslib/tests/test_rpo.py
gslib/tests/test_rsync.py
gslib/tests/test_setmeta.py
gslib/tests/test_shim_util.py
gslib/tests/test_signurl.py
gslib/tests/test_ui.py
gslib/tests/test_user_agent_helper.py
gslib/tests/test_web.py
gslib/tests/test_wrapped_credentials.py
gslib/tests/testcase/__init__.py
gslib/tests/testcase/shim_unit_test_base.py
gslib/utils/shim_util.py

Accessing public data does not require authentication. In gsutil, this works out-of-the-box. In `gcloud storage`, the user has to set `auth/disable_credentials` property to use it without authentication (i.e without setting up an active account). For the shim, in order to not break the workflow of existing users who rely on the gsutil behavior, we will set the `auth/disable_credentials` property automatically if we detect that `gcloud` doesn't have any active account configured.
The change has been tested manually
```
$ CLOUDSDK_CORE_PASS_CREDENTIALS_TO_GSUTIL=1 GCLOUD_BINARY_PATH=/usr/bin/gcloud python3 gsutil.py -o "GSUtil:use_gcloud_storage=True"  ls  gs://pub/test.txt
ERROR: (gcloud.storage.ls) You do not currently have an active account selected.
Please run:
$ gcloud auth login
to …
```

Allow accessing public data with anonymous user when shim is turned ON

---

.gitmodules
gslib/__main__.py
gslib/gcs_json_credentials.py
gslib/tests/test_gcs_json_credentials.py
gsutil.py
setup.py

This change migrates p12 service account authentication flow from oauth2client to google-auth. The change is required, as oauth2client depends upon openSSL for understanding .p12 format keyfiles, in newer version of openSSL they've deprecated the support for .p12 files, due to which oauth2client would throw an error as described in bug b/330533641.
Fixes b/330533641.

Migrates p12 service account authentication flow from oauth2client to google-auth.

---

.github/workflows/ci.yml

This PR fixes Python 3.5 Build failure by adding pip known hosts in the env variables.
Workaround Reference: https://github.com/actions/setup-python/issues/866

Fixes GitHub Workflow build issue.

---

gslib/commands/label.py

Currently, Shim is broken for gsutil label command and also requires pretty printed json in the output. 
This PR fixes the broken shim translation and add indent in the formatter to format shim output.

Fixes label command shim translation issue.

---

gslib/commands/requesterpays.py
gslib/tests/test_rm.py

* requesterpays - Changing Format key according to `gcloud storage buckets describe` output.
* rm: Changing validation for shimmed rm command as shimmed rm command prints more logs line including `Removing buckets:` and `Removing objects`,etc.

Fixes Parity Tests for rm and requesterpays commands.

---

gslib/tests/test_cat.py
gslib/tests/test_rm.py

Recently, Error message for non-matching URLs has been modified in `gcloud storage` tool. This change caused failures in parity tests. 
This PR fixes the failures for `gcloud` validation only and doesn't affect any `gsutil` command implementation or gsutil specific validations.

Fixes parity failures of cat and rm commands.

---

gsutil.py

- Users running Python versions other than 3.5 to 3.11 will see a message:
```
gsutil is supported only for python version 3.5 to 3.11
```
- Added a guide for managing Python versions CL for documentation: [cl/676817175](https://critique.corp.google.com/cl/676817175)
**Note on Tests Failure:**
- Kokoro tests are failing due to an unrelated test,
`metrics.TestMetricsIntegrationTests.testMetricsPosting`
- A bug has been created to track this issue: [b/369285587](https://b.corp.google.com/issues/369285587).

Nudge message 3.11

---

gslib/tests/test_tabcomplete.py

Tab completion in gsutil is currently failing for Python versions greater than 3.11.8, which has been traced back to an upgrade in the argcomplete dependency. This issue is associated with the [v3.3.0 release](https://github.com/kislyuk/argcomplete/releases/tag/v3.3.0).

Skip Tab Complete Tests for python > 3.11.8

---

gsutil.py
setup.py

This PR updates the Python version compatibility for gsutil to support Python 3.8 through 3.12, while dropping support for older versions (3.5, 3.6, and 3.7). The following changes have been made:
- Updated version check in `gsutil.py` to `3.8-3.12`.
- Updated the `python_requires` and `classifiers` in `setup.py` to specify compatibility with Python versions 3.8 to 3.12, removing references to unsupported versions (3.5, 3.6, and 3.7).
These updates align the project with the ongoing effort to support the latest Python versions while ensuring compatibility across all tested platforms.

updating version check to 3.12

---

gslib/commands/perfdiag.py
gslib/commands/signurl.py
gslib/tests/test_compose.py
gslib/tests/test_cp.py
gslib/tests/test_retention.py
gslib/tests/test_rsync.py
gslib/tests/test_shim_util.py
gslib/utils/copy_helper.py
gslib/utils/signurl_helper.py

Added Support for python 3.12
python 3.12 documentation reference: [documentation](https://docs.python.org/dev/whatsnew/3.12.html)
Changes:
- Invalid escape sequence - A backslash-character pair that is not a valid escape sequence now generates a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning), instead of [DeprecationWarning](https://docs.python.org/dev/library/exceptions.html#DeprecationWarning). For example, re.compile("\d+.\d+") now emits a [SyntaxWarning](https://docs.python.org/dev/library/exceptions.html#SyntaxWarning) ("\d" is an invalid escape sequence, use raw strings for regular expression: re.compile(r"\d+.\d+")). In a future Python version, [SyntaxError](https://docs.python.org/dev/library/exceptions.html#SyntaxError) will eventually be …

Py3.12 changes

---

setup.py

Fixes: [issue/1820](https://github.com/GoogleCloudPlatform/gsutil/issues/1820)

update pyopenssl to <= 24.2.1

---

setup.py

This pull request updates the `python_requires` field in the `setup.py` file to `<3.13`, addressing an issue in the `v5.32` release where the constraint was incorrectly set to `<=3.12`. This fix ensures that `gsutil` can be installed via `pip` on `Python` versions `3.12.1` and above.

Change python_requires from <=3.12 to <3.13

---

gslib/tests/test_rsync.py

`gsutil rsync` parity tests are failing in windows machine because of pipe character. Pipe character, `|`, is a special character for winodws cmd and it should escaped while being used in command input. Windows cmd treats `^` character as escape character and can be used to escape pipe character as well but it works only for internal windows commands and fails to escape for external commands. 
It appears that `^^^` string is correctly escaping pipe character even though there is no official windows documentation related to this. 
This PR modifies rsync test check which is testing pipe character in regex input. Since it needs to be escaped for windows machines, I have added a separate condition to format input incase of windows shim only mode.

Fixes parity tests failures in windows machines.

---

gslib/commands/hmac.py

Fixes the spacing inconsistency in hmac list command.
Sample output of gsutil hmac list:
```
+ GOOG1E3BL2EDSOK4PIMAHSDLLEGX33GDQ5YTDCOEHYKPUO24I4RHBZXSCGCWS ACTIVE       sa-hmac2@bigstore-gsutil-testing.iam.gserviceaccount.com
?                                                              ^
```
Sample output of gsutil shim hmac list:
```
- GOOG1E3BL2EDSOK4PIMAHSDLLEGX33GDQ5YTDCOEHYKPUO24I4RHBZXSCGCWS   ACTIVE       sa-hmac2@bigstore-gsutil-testing.iam.gserviceaccount.com
?                                                              ^^^
```
Making the gsutil shim output similar to gsutil output by formatting shim as: `short_list_format = '%s\t%-12s %s'`

Fix Spacing inconsistency in hmac list

---

gslib/commands/hmac.py

Fixes the output mismatch in gsutil hmac get command.
Sample Output of gsutil hmac get:
```
Time Created:          Wed, 25 Sep 2024 09:04:40 GMT
```
Sample Output of gsutil shim hmac get:
```
Time Created:          Wed 25 Sep 2024 09:04:40 GMT
```
Adding extra comma (`,`) in gsutil shim formatter to maintain consistency.

Fix Date formatting parity issue in hmac get command

---

gsutil.py

`Python 3.12` introduced a new `Syntax warning for invalid escape sequence`. Reference: [Python 3.12 Documentation](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes).
Most instances were fixed in [pull/1818](https://github.com/GoogleCloudPlatform/gsutil/pull/1818), except one occurrence in `pyparsing` submodule.
Fix was submitted in upstream as [commit](https://github.com/pyparsing/pyparsing/commit/e26dff1759eecaa81805632d455535a30ce8b495), To upgrade this submodule `gsutil` needs to drop support of `Python 3.8` which is planned for `June 2025`.
This PR silents the warnings temporarily till the original fix is submitted.

Ignore invalid escape sequence SyntaxWarning

---

.github/workflows/ci.yml

Updates the ubuntu version to 24.04 as suggested here https://github.com/actions/runner-images/issues/11101

Update ubuntu version for github workflows

---

gslib/tests/test_Doption.py
gslib/utils/user_agent_helper.py

Adding an invocation id to UserAgent in order to ensure that we can distinguish between each command invocation.

Add invocation id to Gsutil user agent

---

.github/workflows/ci.yml
gsutil.py
setup.py

Updating version check to allow users with `python 3.13` to use `gsutil`.
Drop `python 3.8` from usage.

update version check to 3.13

---

test/ci/kokoro/run_integ_tests_helper.sh

Kokoro MacOS VMs have very old version of pyenv which causes breakages with `Python 3.13`. Modified the script to install the latest `pyenv` version to avoid any similar future breakages.
Also, avoided temporary release versions such as `Python 3.13.4t` etc from `pyenv install --list` to fetch the latest stable release of preferred python version.

Update kokoro tests script to install latest pyenv and stable python release

---

gslib/tests/test_user_agent_helper.py
gslib/utils/user_agent_helper.py

This change appends an addition `-m` to the command information set in UserAgent.
This is being added to understand the usage of the `-m` option across commands.

Add -m option when it is used to user agent to track usage
